### ISSUE TITLE
External FFmpeg issues

### ISSUE THREAD

**Issue by jredd** [Zulko/moviepy#193] opened 2015-08-13 15:53 UTC
I've linked moviepy to an external FFmpeg binary for AAC audio encoding but in the Audio Writer i receive this gem.

File "/usr/local/lib/python2.7/dist-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 109, in write_frames
    "for mp3, 'libvorbis' for ogg...")%(self.codec, self.ext)
AttributeError: FFMPEG_AudioWriter instance has no attribute 'ext'

**Comment by Zulko** [comment] 2015-08-13 16:00
can you provide a minimal example to reproduce the bug ?

**Comment by jredd** [comment] 2015-08-13 17:01
Sorry to have posted. Upon further browsing I came across another persons proper implementation of AAC and that worked wonderfully. Just took a bit to find it. I also messed up on the file name of the temp file. Had given it a .mp3 file extension instead of mp4 but the error message was pointing me in a different direction.

**Comment by baileyspace** [comment] 2016-04-15 05:07
@jredd could you post the correct AAC implementation? I'm up the same creek.

**Comment by jredd** [comment] 2016-04-15 05:22
@baileyspace 

As I said above I messed up on the file extensions but if you want an example of how I ended up with the settings well here you go

.write_videofile(
    self.downloadPath + finalFileName,
    codec='libx264',
    audio_codec="aac",
    bitrate='650k',
    remove_temp=True,
    temp_audiofile=os.path.join(self.downloadPath,'{}.mp4'.format(uuid.uuid4().__str__())), fps=20,
        ffmpeg_params = ['-movflags','faststart', '-profile:v', 'main', '-level', '3.1', '-pix_fmt', 'yuv420p',
                                      '-minrate', '650k', '-maxrate', '650k'])

**Comment by baileyspace** [comment] 2016-04-15 05:44
Thanks!

**Comment by jredd** [comment] 2016-04-16 20:32
np hope that worked out for ya!

**Comment by baileyspace** [comment] 2016-04-17 20:07
Sure did. I was trying to get the video encoding right for Twitter. When I added the audio_codec param I started getting the 'ext' error. So, I switched my temp_audiofile path to end in m4a instead of mp3 as you suggested AND I added the codec='libx264' param. After that everything works just fine.

**Comment by kerstin** [comment] 2017-02-18 01:07
Looks like this was solved. Closing.

**Closed by kerstin** 2017-02-18 01:07 UTC
