### ISSUE TITLE
write_videofile get stuck!

### ISSUE THREAD

**Issue by ImJeremyHe** [Zulko/moviepy#803] opened 2018-05-28 08:09 UTC
[MoviePy] >>>> Building video 20150222a.ts
[MoviePy] Writing audio in 20150222aTEMP_MPY_wvf_snd.mp3
 70%|██████▉   | 6018/8627 [00:06<00:02, 921.73it/s]

It will be always at 70%.
It seems that it can't read anything from the video file. And I have already updated moviepy. 
What should i do?
<pre><code>
def cut(videofile, segments, **kwargs):
    length = len(segments)
    index = "abcdefghijklmnopqrstuvwxyz"
    for i in range(length):
        new_name = splitext(basename(videofile))[0] + index[i] + '.ts'
        video = VideoFileClip(videofile).subclip(t_start=segments[i][0], t_end=segments[i][1])
        video = video.fl(lambda gf, t: gf(t)[:, 215:655, :])
        video.write_videofile(new_name, codec="libx264", **kwargs)

cut("20150222.ts", [(3521.48, None)], progress_bar=True, fps=24)
</code></pre>

**Comment by ImJeremyHe** [comment] 2018-05-30 02:32
I fucked up this problem by using ffmpeg to cut the video.
ffmpeg -y -ss t_start -t duration -accurate_seek -i video_file -codec copy output_file

**Comment by GarciaDelMolino** [comment] 2018-07-10 08:45
Did you try forcing a `KeyboardInterrupt` to inspect where was it stuck?

I'm facing a similar problem when calling `iter_frames` for files corrupted only partly (I'm doing that for a pretty long list of files and cannot inspect all of them visually). At the first corrupted frame found (frame `6988` in the case below), `self.proc.stdout.read(nbytes)` in [FFMPEG_VideoReader](https://github.com/Zulko/moviepy/blob/a002df34a1b974e73cbea02c2f436c94b81fbc39/moviepy/video/io/ffmpeg_reader.py#L120) `read_frame` waits eternally for response, so my batch process never finishes:

```
In [1]: from moviepy.video.io.VideoFileClip import VideoFileClip
   ...: with VideoFileClip("MyCorruptedVideofile.mp4") as clip:
   ...:     for img in clip.iter_frames():
   ...:         pass
   ...:
26%|███                      | 6988/26856 [00:40<01:53, 174.53it/s]
^C---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-5-2d2ecdf30a64> in <module>()
      1 with VideoFileClip(video_files[0]) as clip:
----> 2     for img in clip.iter_frames(clip.fps, progress_bar=True):
      3         pass
      4 
[...]
/home/ubuntu/anaconda2/lib/python2.7/site-packages/moviepy/Clip.pyc in generator()
    473         def generator():
    474             for t in np.arange(0, self.duration, 1.0/fps):
--> 475                 frame = self.get_frame(t)
    476                 if (dtype is not None) and (frame.dtype != dtype):
    477                     frame = frame.astype(dtype)
[...]
/home/ubuntu/anaconda2/lib/python2.7/site-packages/moviepy/video/io/ffmpeg_reader.pyc in get_frame(self, t)
    181             else:
    182                 self.skip_frames(pos-self.pos-1)
--> 183             result = self.read_frame()
    184             self.pos = pos
    185             return result

/home/ubuntu/anaconda2/lib/python2.7/site-packages/moviepy/video/io/ffmpeg_reader.pyc in read_frame(self)
    118         nbytes= self.depth*w*h
    119 
--> 120         s = self.proc.stdout.read(nbytes)
    121         if len(s) != nbytes:
    122 

KeyboardInterrupt: 
```

I overcome the issue by wrapping `iter_frames` with a `Timer`:
```
from moviepy.video.io.VideoFileClip import VideoFileClip
from threading import Timer
with VideoFileClip("MyCorruptedVideofile.mp4") as clip:
    def timeout_trigger():
        clip.reader.proc.kill()
        clip.reader.proc = None
        clip.reader.lastread = None
    timer = Timer(.5, timeout_trigger)
    timer.start()
    for img in clip.iter_frames():
        timer.cancel()
        if img is None:
             print "corrupted file"
        else:
             #Do stuff with img
        timer = Timer(.5, timeout_trigger)
        timer.start()
    timer.cancel()
```

but it'd be nice to have an internal timeout process for the `stdout.read()` call...

**Comment by ImJeremyHe** [comment] 2018-07-10 12:56
@GarciaDelMolino 
Hello! I think you're right!

**Comment by guerda** [comment] 2018-09-26 09:03
I have a similar problem as @ImJeremyHe. ffmpeg tells me about truncated frames: 
`[h264 @ 0000000014ae4560] SEI type 5 size 672 truncated at 671` etc.

Are there any options to let ffmpeg be more tolerant about corrupt frames?

**Comment by LiorRaines** [comment] 2020-05-31 13:53
I faced the same problem - the source of the problem is that the subprocess that runs FFmpeg writing stdout and stderr to the pipe. So corrupted video will cause the pipe to fill up by the writing to stdout.
possible solutions:
1) change the file readers.py the configurations of the subprocess to stderr: DEVNULL  
2) first run the video in ffmpeg like ffmpeg -i input.mp4 output.mp4 and use the output video

**Comment by pouriyaGhasemi** [comment] 2021-01-04 12:05
I'm facing a similar problem when calling write_videofile(). 
according to what you told about stderr and stdout, I set **logger=None** and threads=5 to increase threads, when calling write_videofile(), as result every thing is all right.

**Comment by keikoro** [comment] 2022-01-14 18:08
As per the above comments, it seems like solutions to this problem were found -> closing.

**Closed by keikoro** 2022-01-14 18:08 UTC
Labels: question, video, lib-FFmpeg

**Comment by verigle** [comment] 2024-03-28 02:35
> I'm facing a similar problem when calling write_videofile(). according to what you told about stderr and stdout, I set **logger=None** and threads=5 to increase threads, when calling write_videofile(), as result every thing is all right.

but I set **logger=None and threads=os.cpu_count()** does net work, also stuck
