### ISSUE TITLE
Use  GPU

### ISSUE THREAD

**Issue by guduxingzou** [Zulko/moviepy#1382] opened 2020-11-23 11:20 UTC
wish  use GPU，cpu is slow！ THANKS!!!
Chinese：
期待可以使用GPU进行渲染，CPU太慢了，谢谢开发者们的辛勤工作！

**Comment by wiebecommajonas** [comment] 2020-12-17 09:15
I would also like the ability to work with my GPU rather than CPU.

**Comment by keikoro** [comment] 2022-01-05 23:40
Closing this as duplicate of several comments and emoji upvotes in #1089.

**Closed by keikoro** 2022-01-05 23:40 UTC
Labels: feature-request
