### ISSUE TITLE
Help!!!! errors during installation on Mac

### ISSUE THREAD

**Issue by superkoma** [Zulko/moviepy#788] opened 2018-05-04 05:06 UTC
I use both two methods to install moviepy on my Mac. One is using "(sudo) pip install moviepy", the other is  downloading this moviepy project firstly, then using "(sudo) python setup.py install". But both two methods are error with the same warning:

```
**error in moviepy setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.**
```

I find 'extras_require' in setup.py:
extras_require=extra_reqs

then, I find:
extra_reqs = {
    "optional": optional_reqs,
    "doc": doc_reqs,
    "test": test_reqs
    }

but I don't know how to handle this situation, so would anyone please give me a favor? Thanks a lot.

**Comment by tburrows13** [comment] 2018-05-04 08:33
This looks like a duplicate of #771.

Try running `pip install --upgrade setuptools` to update setuptools to the latest version.

**Comment by superkoma** [comment] 2018-05-04 09:32
I try to run “(sudo) pip install —upgrade setuptools”, but I met errors as follows:
I don’t know what’s the problem, thank you.
Installing collected packages: setuptools
  Found existing installation: setuptools 18.5
    Uninstalling setuptools-18.5:
Could not install packages due to an EnvironmentError: [('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', '/private/tmp/pip-uninstall-wJobzQ/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', "[Errno 1] Operation not permitted: '/private/tmp/pip-uninstall-wJobzQ/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', '/private/tmp/pip-uninstall-wJobzQ/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', "[Errno 1] Operation not permitted: '/private/tmp/pip-uninstall-wJobzQ/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', '/private/tmp/pip-uninstall-wJobzQ/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', "[Errno 1] Operation not permitted: '/private/tmp/pip-uninstall-wJobzQ/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', '/private/tmp/pip-uninstall-wJobzQ/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', "[Errno 1] Operation not permitted: '/private/tmp/pip-uninstall-wJobzQ/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', '/private/tmp/pip-uninstall-wJobzQ/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', "[Errno 1] Operation not permitted: '/private/tmp/pip-uninstall-wJobzQ/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib'")]

**Comment by superkoma** [comment] 2018-05-04 10:12
I found an answer on stackoverflow: [https://stackoverflow.com/questions/36996629/sudo-pip-install-setuptools-upgrade-error](url), and `pip install --upgrade setuptools --user python`works perfectly to handle the problem.

Thank you a lot. That I missed #771 is my fault and sorry to bother you.

Thank you again.

**Closed** 2018-05-05 06:25 UTC

**Comment by maribethpierce** [comment] 2018-10-12 15:04
Thanks superkoma! This is exactly what I needed

**Comment by superkoma** [comment] 2018-10-13 02:54
>           Thanks superkoma! This is exactly what I needed
I felt happy if it helped you.
