### ISSUE TITLE
file_to_subtitles: support for unicode

### ISSUE THREAD

**Issue by kempeng** [Zulko/moviepy#1393] opened 2020-12-28 23:06 UTC
Not sure if this is a bug or feature request:
I was trying to create a SubtitlesClip() from a .srt file with Spanish subtitles. The special characters from the .srt did not convert properly:
([5.169, 9.06], 'a su página de inicio. Aquí encontrará todas las tareas')
was converted into:
([5.169, 9.06], 'a su pÃ¡gina de inicio. AquÃ\xad encontrarÃ¡ todas las tareas')

The problem is with how the function
file_to_subtitles()
opens the srt file.

changing line 153 in subtitles.py from:
with open(filename,'r') as f:
to
with open(filename,'r',encoding="utf-8") as f:
solved the problem

**Comment by tburrows13** [comment] 2021-01-12 20:59
Closing as duplicate of #1394.

**Closed by tburrows13** 2021-01-12 20:59 UTC
Labels: feature-request
