### ISSUE TITLE
Wrong number of frames in .gif file

### ISSUE THREAD

**Issue by avdeevvadim** [Zulko/moviepy#181] opened 2015-07-03 01:38 UTC
Thank you for MoviePy, excellent project :)

I have a problem with correct number of frames in .gif file.
I have a list of images and want to construct an animated .gif file from these pictures. I use ImageSequenceClip and sometimes receive a file with the wrong number of frames.

**MWE**:

``` python
import numpy as np
import moviepy.editor as mpy

frames = 18
fps = 10
height = 10
width = 10
channels = 3

gif = np.zeros((frames, height, width, channels), np.uint8)

gif = list(gif)

animation = mpy.ImageSequenceClip(gif, fps = fps)
animation.write_gif('out.gif')
```

I expected to get out.gif with 18 frames, but after building file with imageio I received out.gif with 19 frames.
What is the problem here?

I use imageio 1.3, moviepy 0.2.2.11 and Python 3.4.3.

**Comment by neuroglobin** [comment] 2016-05-11 20:29
Hello, 
I'v met the same problem and believe this problem is not caused by moviepy itself. 
Even I specified fps or duration directly in the `freeimagemulti.py` of imageio 1.3 (which moviepy calls), the same wrong-number-frame problem happened. I am not sure whether this problem is solved in newer version of imageio.

**Comment by kerstin** [comment] 2017-02-17 23:47
I'm closing this issue because by the sounds of it, the problem reported here was not caused by MoviePy.

If it is/was documented in the [imageio](https://github.com/imageio/imageio) repo, please feel free to link any relevant info for future reference/in case others run into similar issues.

**Closed by kerstin** 2017-02-17 23:47 UTC
