### ISSUE TITLE
'set_position' not working properly with variable having number but working when passing static number 

### ISSUE THREAD

**Issue by pankajmcs** [Zulko/moviepy#2078] opened 2023-12-07 10:15 UTC
Hi,
   Actually I am creating video clip by stiching multiple image clips with slide effect, for effect I am using Lambda when passing static numbers at x,y position all works fine but when I am passing custom variable with proper int type at x,y cordinates its not working properly, kindly let me what causing this issue.
Code:
  slide1 = ImageClip(img.jpg ,duration=3).set_duration(3).set_start(timer * 3 ).set_position(lambda t: ( 50 + (300-25)*(t/1)  if (50 + (300-20)*(t/1) < xPos1) else xPos1,yPos1)).crossfadein(.5).fx(normalize_image)

**Comment by SohamTilekar** [comment] 2023-12-21 09:51
Bro Same Problem I have a Solution. #2084 [Bug](https://github.com/Zulko/moviepy/issues/2084) Bug Report Hase the jugad(Temporary Solution) for the Problem

**Comment by keikoro** [comment] 2024-02-10 20:04
Closing as duplicate of the linked issue. Thx, @SohamTilekar for pointing it out.

**Closed by keikoro** 2024-02-10 20:04 UTC
Labels: question
