### ISSUE TITLE
ImageMagick write gif success but no file found 

### ISSUE THREAD

**Issue by lisongx** [Zulko/moviepy#113] opened 2015-01-16 16:19 UTC
`imageio`  throw segmentation fault

**Comment by seansay** [comment] 2015-01-16 16:20
also, xxxx.ficache seems to be in the same folder I write gif to

**Comment by seansay** [comment] 2015-01-16 16:21
wrote to video file works fine

**Comment by Zulko** [comment] 2015-01-16 16:36
Thanks for the report. Can you provide the following ?

- Your OS and python version
- The code that you are using (or at least a bit of it),
- The error that you get (or do you really have no message at all apart from the seg fault ?)
- Your moviepy version (I imagine it's the last one).

I am calling @almarklein, the imageio author, into the discussion, it may concern him.

Cheers !

**Comment by almarklein** [comment] 2015-01-16 22:36
The `xxxx.ficache` is an artifact of freeimage; it may use a temporary file to preserve RAM. I suppose you see it because it segfaults before FreeImage had a chance to clean it up. Other than that, there's not much to tell without more information.

**Comment by almarklein** [comment] 2015-01-16 22:37
Oh wait. It might actually be fixed in current master. Someone fixed a similar bug recently: https://github.com/imageio/imageio/pull/53

**Comment by Zulko** [comment] 2015-01-24 10:09
@seansay Any improvement ? If not, can you give a few more infos ?

**Comment by Ziewvater** [comment] 2015-02-02 07:19
I'm having this same issue as well. Trying to use `write_gif`with default of `program='imageio'` leads to a segmentation fault with an output that looks like this each time:
```
MoviePy] Building file 54.gif with imageio
|----------| 0/77   0% [elapsed: 00:00 left: ?, ? iters/sec][1]    95953 segmentation fault  python scriptname.py
```

Using ImageMagick avoids segmentation fault, but results in a success message, but no gif file to be found on my machine. Code and printout looks like this:
```
from moviepy.editor import *
video = VideoFileClip("Movie File Name.mp4").resize(0.3).subclip(3,5)
video.write_gif("test.gif", program="ImageMagick")

[MoviePy] >>>> Building file test.gif
[MoviePy] Generating GIF frames...
[MoviePy] Optimizing the GIF with ImageMagick...
[MoviePy] >>>> File test.gif is ready !>>>
```

Looks like I'm using moviepy 0.2.2.5. Also, if it helps, I was playing around to see what I was doing wrong and revisited an older project using an older version of moviepy (0.2.1.8.02), and the segmentation fault issues did not occur when using `to_gif`. In the more recent version, however, the segmentation fault occurred when using both `to_gif` and `write_gif`. I'm using Python 2.7.9, and on OSX 10.10

**Comment by almarklein** [comment] 2015-02-04 15:19
imageio 1.1 is now available. The error should be resolved in this release.

**Comment by Ziewvater** [comment] 2015-02-04 17:33
Upgrading to imageio1.1 fixed the crash when writing to gif without the `program` option set, thanks!  The ImageMagick problem persists.

**Comment by almarklein** [comment] 2015-02-04 22:02
> Upgrading to imageio1.1 fixed the crash when writing to gif without the program option set, thanks!

Good! Thanks for checking!

**Comment by Lunderberg** [comment] 2016-02-15 20:28
I can confirm that the ImageMagick issue is still present.  Below is code that reproduces the error.  It attempts to create a short gif fading from black to white.  After running the script, `output_imageio.gif` exists, but `output_imagemagick.gif` does not.

```python
#!/usr/bin/env python3

from moviepy.editor import VideoClip
import numpy

def make_frame(t):
    frame = numpy.empty(shape=(300,200,3),dtype='int')
    frame.fill(int(t*64))
    return frame

clip = VideoClip(make_frame, duration=4)
clip.write_gif('output_imageio.gif', program='imageio', fps=10)
clip.write_gif('output_imagemagick.gif', program='ImageMagick',fps=10)
```

Python v3.4.3
moviepy v0.2.2.11 (Current from PyPI)
ImageMagick v8:6.7.7.10-6ubuntu3 (From ubuntu repository)

**Comment by Zulko** [comment] 2016-02-17 10:22
It may be due to the fact that the default optimization in `write_gif` is an `imageio` optimization. Can you try to change the optimization to "OptimizePlus" when you have `program=ImageMagick` ?

**Comment by Lunderberg** [comment] 2016-02-17 23:20
When using `opt=OptimizePlus` in the command using ImageMagick, the gif is generated.  When no optimization algorithm is specified, should it default to one that is applicable to the program given?

**Comment by kiddick** [comment] 2019-01-27 16:53
same here

**Comment by KiLLAAA** [comment] 2019-06-14 20:23
its an old bug in MoviePy, i have fixed it, wait ;-)

**Comment by KiLLAAA** [comment] 2019-06-15 11:33
Fix here -> https://github.com/Zulko/moviepy/pull/972

**Comment by tburrows13** [comment] 2019-10-01 13:33
Should be fixed now, let us know if there are still problems.

**Closed** 2019-10-01 13:32 UTC
Labels: 3rd-party, bug, images

**Comment by siu3334** [comment] 2021-02-17 10:04
This issue is still present in latest version of moviepy version available on pypi, as time of this writing. When using write_gif() with ImageMagick as program, it says gif is ready but gif is nowhere to be found on disk.

**Comment by MrMrMr** [comment] 2021-03-04 23:27
I'm having the same issue as siu.

**Comment by QQ860777607** [comment] 2021-04-23 06:44
Set tempfiles = True when using program='ImageMagick'

**Comment by CaseGuide** [comment] 2021-08-24 15:28
I can confirm that @QQ860777607's comment works. Also if someone is landing here wondering about which optimizer to use. For a Gif that displays some static images and text with a small window of high motion video, (think powerpoint presentation) I found that the below params decrease filesize by >90% AND increased video quality.
```
    opt='OptimizeTransparency', 
    program='ImageMagick',
    tempfiles=True
```
