### ISSUE TITLE
transparency bug in concatenate_videoclips()

### ISSUE THREAD

**Issue by clauswilke** [Zulko/moviepy#103] opened 2014-12-12 14:44 UTC
The function concatenate_videoclips() has three transparency bugs:
1. The default should be `transparent=True`, not `transparent=False`. The purpose of this function is simply to stitch multiple videoclips together. It makes no sense to remove transparency in the process by default.
2. If I set `transparent=True`, the function crashes. The offending line is line 85 in:
   https://github.com/Zulko/moviepy/blob/master/moviepy/video/compositing/concatenate.py
   The variable `clips` that is used in the list comprehension is not defined. It should be `clipslist`.
3. If I set `transparent=False`, I would expect that transparency is replaced by the background color given as `bg_color` argument. As far as I can see, that is not the case, however. Transparency is replaced by black.

**Comment by earney** [comment] 2017-02-22 20:25
closing.. this issue looks resolved.

**Closed by earney** 2017-02-22 20:25 UTC
Labels: bug

**Comment by kerstin** [comment] 2017-11-25 16:57
@earney I'm guessing #104 can then also be closed?

**Comment by earney** [comment] 2017-11-26 15:39
I am not sure if issue 104 can be closed.  We will have to verify, if the issue is still valid.

**Comment by UnWaDo** [comment] 2021-04-24 08:50
It's still an issue
I was not able to figure out how to fix it
