### ISSUE TITLE
Examples resources videos directory missing 

### ISSUE THREAD

**Issue by meiry** [Zulko/moviepy#975] opened 2019-06-16 20:18 UTC
I clone the latest code , install all dependencies , even 88 tests passed , 
but now i trying to execute the examples scripts , but there is no videos directory .
from where all the resources are loaded .
this is how my dir tree looks like :
![image](https://user-images.githubusercontent.com/1107316/59569056-d97a4180-908c-11e9-943d-2c64ad9f54ac.png)

**Comment by mondeja** [comment] 2021-01-13 18:32
Closing as duplicate of #338.

**Closed by mondeja** 2021-01-13 18:32 UTC
Labels: examples
