### ISSUE TITLE
Video with rotation metadata is stretched

### ISSUE THREAD

**Issue by cvn** [Zulko/moviepy#682] opened 2017-12-10 22:35 UTC
Hello all,

I'm processing some vertical videos shot on an iPhone. With moviepy 0.2.3.2 and this code:
```python
with VideoFileClip("ficus_vertical.mp4") as clip:
    clip.write_videofile('output.mp4')
```
I get this output | I expected this
--- | ---
<img src="https://user-images.githubusercontent.com/774864/33809834-eca60b66-ddb1-11e7-8606-951c7d4f38be.jpg" width="200"> | <img src="https://user-images.githubusercontent.com/774864/33809836-f23d2834-ddb1-11e7-933d-14060b626b4a.jpg" height="200">

Source file: [ficus_vertical.mp4](https://github.com/earney/moviepy_media/blob/master/tests/videos/ficus_vertical.mp4?raw=true)

The problem is that ffmpeg is autorotating the video according to the metadata, but moviepy is sizing it to the pre-rotated frame size. This problem is also mentioned by #577. Autorotate has been enabled by default [since ffmpeg 2.7](https://stackoverflow.com/a/30899179/490592). 

I have a branch that fixes the issue, and also allows for autorotate to be disabled. I will submit a PR after my test media is added to the moviepy_media repo.

**Comment by pkarp0** [comment] 2017-12-28 18:23
There is a workaround described here: 
https://github.com/Zulko/moviepy/issues/586

**Comment by cvn** [comment] 2018-01-04 20:39
Thanks, @pkarp0. I hope the issue will be fixed soon, whether by my PR or another means, but the workarounds are useful in the meantime.

**Comment by pkarp0** [comment] 2018-01-04 22:27
@cvn Awesome. Perhaps you could take a look at my issue next:
https://github.com/Zulko/moviepy/issues/680

**Comment by mondeja** [comment] 2021-01-25 10:11
Duplicate of #586

**Closed by mondeja** 2021-01-25 10:11 UTC
Labels: 3rd-party, video
