### ISSUE TITLE
Gif loop skips first frame

### ISSUE THREAD

**Issue by ignaciosy** [Zulko/moviepy#277] opened 2016-03-15 16:52 UTC
Hi, i've been using moviepy to convert gifs to video (mp4), and loop them a few times. It works but i recently noticed that the first frame of the animated gif only shows up in the first display.
For example, if it has 4 frames:
Gif: f1 f2 f3 f4
mp4: f1 f2 f3 f4 f2 f3 f4 f2 f3 f4 f2 f3 f4.......
The code i'm using in Django is:

```
import moviepy.editor as mp

file = "path/to/gif.gif"
clipdir = "path/to/video.mp4"
clip = mp.VideoFileClip(file)
clip = clip.loop(n=6)
clip.write_videofile(clipdir, codec='libx264', fps=clip.fps, audio=False)
```

Didn't find any related issues, and the console doesn't throw any errors/warnings, so i'm not sure what the problem might be.
Also searched for loop.py, but

```
if n:
        duration = n*self.duration
```

Seems pretty straightforward.

Thanks in advance.

PS: your lib is great! Has a lot a lot of implementations and tweeks i've been fiddling with :)

**Comment by mondeja** [comment] 2021-01-21 14:29
I can't reproduce the error with master version and since moviepy has changed a lot since this issue was open, I'm closing it. Feel free to reopen it if you continue experiencing this bug.

**Closed by mondeja** 2021-01-21 14:29 UTC
Labels: images
