### ISSUE TITLE
 AudioFileClip

### ISSUE THREAD

**Issue by kindeQi** [Zulko/moviepy#448] opened 2017-02-26 09:50 UTC
**My code is**
`Aclip= AudioFileClip(audioPath)`

**the error message is that**
`File "D:/Code Store/Smart BGM2/Smart BGM/Smart BGM/PYTHON/VideoAndAudio.py", line 106, in test
    Aclip= AudioFileClip(audioPath)
  File "C:\Python27\lib\site-packages\moviepy\audio\io\AudioFileClip.py", line 63, in __init__
    buffersize=buffersize)
  File "C:\Python27\lib\site-packages\moviepy\audio\io\readers.py", line 56, in __init__
    infos = ffmpeg_parse_infos(filename)
  File "C:\Python27\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 306, in ffmpeg_parse_infos
    result['video_fps'] = float(line[match.start():match.end()].split(' ')[1])
AttributeError: 'NoneType' object has no attribute 'start'`
**AttributeError: 'NoneType' object has no attribute 'start :it's pycharm's feedback**

**With the help of breakpoint, I found that:**
`        try:
            match = re.search("( [0-9]*.| )[0-9]* tbr", line)
            tbr = float(line[match.start():match.end()].split(' ')[1])
            result['video_fps'] = tbr`

**match.start() is wrong, no return,**

**Here is the code in python-skeletons\re.py**
`    def start(self, group=0):
        """Return the index of the start of the substring matched by group.

        :type group: int | bytes | unicode
        :rtype: int
        """
        pass

    def end(self, group=0):
        """Return the index of the end of the substring matched by group.

        :type group: int | bytes | unicode
        :rtype: int
        """
        pass`
**I'm wondering if there is something wrong with the function start** 
**Could anyone give me a hand?**

**Comment by kindeQi** [comment] 2017-02-26 14:55
**Problem solved!!**

At first the audio type is **.mp3** and then I tried **.flac**, both of these two kinds are reported wrong.
_match_ is wrong in this line, A nonetype error:
`line[match.start():match.end()].split(' ')[1]`
However, It works when the audio type is **.wav**!! 

**Question:**
I'm totally a beginner to moviepy and I wonder why that happened? 
It's wired because FFmpeg could handle .mp4 files and I noticed that the moviepy is using ffmpeg to do a series of operations about audioes.

Ps: In this case, **The environment is python2.7.13+moviepy0.2.2.13+FFmpeg version: 20170223-dcd3418**

**Comment by earney** [comment] 2017-02-26 15:01
That is great news!  I will look into this and try to figure out an explanation.  At the very least we need better error messages..

**Comment by earney** [comment] 2017-02-26 20:53
In your last comment you state that the audio type was .mp3 then .flac, and then you tried .wav?   Did you use the codec optional argument for this?  The code you shared above only has the audio file name, and no other arguments.

**Comment by earney** [comment] 2017-02-26 21:19
In other words, how did you specify the extension.. was it in the filename?

**Comment by kindeQi** [comment] 2017-02-27 00:21
Yes, I specify the extension in filename

**Comment by earney** [comment] 2017-02-27 01:09
kindeQi,

I'm trying to reproduce your error, and I've tried the following and receive no error.  Does this code produce an error for you?

```
import os
from moviepy.editor import *

download_webfile("https://archive.org/download/ainst-alien/alien140.wav",
                 "alien140.wav")

os.rename("alien140.wav", "alien140.mp3")
_clip = AudioFileClip("alien140.mp3")

os.rename("alien140.mp3", "alien140.flac")
_clip = AudioFileClip("alien140.flac")

```

**Comment by djh-** [comment] 2017-02-27 01:48
Hey @earney, I'm having the same issue. Your test code worked for me no problem. But this does not work for me:

```python
import os
from moviepy.editor import *

my_clip = AudioFileClip('test.mp3')
```

test.mp3 is a renamed mp3 file from this free album (specifically track 12, Challengers)
http://promo.na.leagueoflegends.com/en/music-of-league/

I'm using Python 3.6 with the latest moviepy 0.2.2.13

This is the stack trace:
```
Traceback (most recent call last):
  File "/Users/daniel/Documents/Dev/Projects/AutoClipper/venv/lib/python3.6/site-packages/moviepy/video/io/ffmpeg_reader.py", line 301, in ffmpeg_parse_infos
    tbr = float(line[match.start():match.end()].split(' ')[1])
ValueError: could not convert string to float: '90k'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "test.py", line 4, in <module>
    my_clip = AudioFileClip('test.mp3')
  File "/Users/daniel/Documents/Dev/Projects/AutoClipper/venv/lib/python3.6/site-packages/moviepy/audio/io/AudioFileClip.py", line 63, in __init__
    buffersize=buffersize)
  File "/Users/daniel/Documents/Dev/Projects/AutoClipper/venv/lib/python3.6/site-packages/moviepy/audio/io/readers.py", line 55, in __init__
    infos = ffmpeg_parse_infos(filename)
  File "/Users/daniel/Documents/Dev/Projects/AutoClipper/venv/lib/python3.6/site-packages/moviepy/video/io/ffmpeg_reader.py", line 306, in ffmpeg_parse_infos
    result['video_fps'] = float(line[match.start():match.end()].split(' ')[1])
AttributeError: 'NoneType' object has no attribute 'start'
```

**Comment by earney** [comment] 2017-02-27 02:19
Thanks..  I'll give your audio file a try.

**Comment by earney** [comment] 2017-02-27 02:48
I can reproduce the error.  We will look into this ASAP.  Thanks for letting is know.

**Comment by djh-** [comment] 2017-02-27 03:06
Thanks, looks like there's a potential fix here. It worked for me.
https://github.com/Zulko/moviepy/pull/225

**Comment by kindeQi** [comment] 2017-02-27 07:27
@earney **Thanks for your help**
Your code works.No Error.
But I tried several audioes again
My code is like this:
`   
    import os
    from moviepy.editor import *
    os.chdir(DIR)
    counter1=0
    counter2=0
    N1=[]
    N2=[]
    for file in glob.glob("*.mp3"):
        try:
            AudioFileClip(file)
            counter1+=1
            N1.append(file)
        except:
            counter2+=1
            N2.append(file)
        finally:
`
Some of them worked and others failed

Here is a link for the audioes in my case
link：http://pan.baidu.com/s/1hsbsFOS password：n7qn
I'm not sure uploading these songs and sharing them is appropriate or not, if not, tell me and I will delete them ASAP

**Comment by earney** [comment] 2017-02-27 13:36
KindeQi,

Have you looked at pull request # 225?     I don't know your coding ability, but you could try to update the file at [https://github.com/Zulko/moviepy/pull/225/files](https://github.com/Zulko/moviepy/pull/225/files)  and see if that fixes your problem?

**Comment by kindeQi** [comment] 2017-02-27 14:28
Thanks so much, earney!!!
I updated that file according to pull request # 225
And it works perfetly

**Comment by earney** [comment] 2017-02-27 14:41
Awesome!   I'll look into pushing this pull request as soon as possible so that people don't have this problem in the future.

**Comment by earney** [comment] 2017-02-27 14:41
kindeQi..   since this works, I assume we can close this issue?

**Comment by kindeQi** [comment] 2017-02-27 14:49
Of course, Thanks so much

**Closed** 2017-02-27 14:49 UTC
