### ISSUE TITLE
Where are the files for the examples?

### ISSUE THREAD

**Issue by x13machine** [Zulko/moviepy#807] opened 2018-06-02 23:31 UTC
I can't find where to download them.

**Comment by anandkpandey1** [comment] 2018-06-05 19:04
please navigate to <https://github.com/Zulko/moviepy/tree/master/examples>

**Comment by x13machine** [comment] 2018-06-05 22:13
I meant the movie/images/sound files.

**Comment by tburrows13** [comment] 2020-04-27 00:59
#1133

**Comment by mondeja** [comment] 2021-01-13 18:31
Closed as duplicate of #338.

**Closed by mondeja** 2021-01-13 18:31 UTC
Labels: examples, question
