### ISSUE TITLE
TextClip.list('font') error

### ISSUE THREAD

**Issue by lingting** [Zulko/moviepy#1262] opened 2020-07-14 12:33 UTC
run `TextClip.list('font')`

#### Expected Behavior
['Agency-FB', 'Agency-FB-Bold', 'Algerian', 'Arial',  .... ]

#### Actual Behavior
UnicodeDecodeError:'utf-8' codec can't decode byte 0xb7 in position 8: invalid start byte

#### Steps to Reproduce the Problem
Use Chinese window, the system default encoding is gbk, this time execute TextClip.list('font') will throw an exception
`UnicodeDecodeError:'utf-8' codec can't decode byte 0xb7 in position 8: invalid start byte`

#### Specifications

  - Python 3.8:
  - Moviepy 1.0.3:
  - Platform windows:
  - Platform 10:

**Comment by tburrows13** [comment] 2020-07-15 23:00
I think that this is a duplicate of #1250, so try the fix there.

**Comment by lingting-gzm** [comment] 2020-07-19 09:07
Did you mean to add `encoding="utf-8"` to the header of the file? I use python3, and even if I add it, it doesn’t work. I only need to directly modify the `utf-8` in the code to `gbk` and use this method to avoid abnormalities.

**Comment by lingting-gzm** [comment] 2020-07-19 09:07
> 

Did you mean to add `encoding="utf-8"` to the header of the file? I use python3, and even if I add it, it doesn’t work. I only need to directly modify the `utf-8` in the code to `gbk` and use this method to avoid abnormalities.

**Closed** 2021-01-21 15:52 UTC
Labels: bug, text
