### ISSUE TITLE
TypeError: must be real number, not NoneType

### ISSUE THREAD

**Issue by alejopaullier96** [Zulko/moviepy#1824] opened 2022-09-03 03:26 UTC
I am facing the following problem: `TypeError: must be real number, not NoneType` when I try executing my code:
```
with VideoFileClip(video_path) as video:
    new = video.subclip(start_time, end_time)
    new.write_videofile(output_path)
```
I have tried upgrading/downgrading moviepy, ffmpeg, decorator, etc and the error persists.

### My versions

- decorator==4.4.2
- ffmpeg==1.4
- moviepy==1.0.3

**Comment by keikoro** [comment] 2022-09-09 21:00
You unfortunately didn't provide error logs, but it sounds like this may be a duplicate of #1625. Do report back if it isn't.

**Closed by keikoro** 2022-09-09 21:00 UTC
Labels: bug, video
