### ISSUE TITLE
MoviePy error: FFMPEG encountered the following error while writing file

### ISSUE THREAD

**Issue by opc241** [Zulko/moviepy#1968] opened 2023-05-08 12:49 UTC
write_videofile() generates the following error:

`An error has occurred: [Errno 32] Broken pipe
MoviePy error: FFMPEG encountered the following error while writing file 7 | Jenke.CrimeTEMP_MPY_wvf_snd.mp3:
b'7 | Jenke.CrimeTEMP_MPY_wvf_snd.mp3: Invalid argument\r\n'
In case it helps, make sure you are using a recent version of FFMPEG (the versions in the Ubuntu/Debian repos are deprecated).`

I am using: 
moviepy v1.0.3
imageio v2.28.1
imageio-ffmpeg v0.4.8 (Downgrade to v0.2.0 does not help)

**Comment by Cinemagine** [comment] 2023-06-05 20:17
Same issue, running in Flask on render.com:
moviepy==1.0.3
imageio==2.31.0
imageio-ffmpeg==0.4.8
```
t:  11%|█         | 56/528 [00:03<00:58,  8.09it/s, now=None][2023-06-05 15:55:28,477] ERROR in app: Exception on /demo2 [GET]
Jun 5 04:55:28 PM  Traceback (most recent call last):
Jun 5 04:55:28 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/moviepy/video/io/ffmpeg_writer.py", line 136, in write_frame
Jun 5 04:55:28 PM      self.proc.stdin.write(img_array.tobytes())
Jun 5 04:55:28 PM  BrokenPipeError: [Errno 32] Broken pipe
Jun 5 04:55:28 PM  
Jun 5 04:55:28 PM  During handling of the above exception, another exception occurred:
Jun 5 04:55:28 PM  
Jun 5 04:55:28 PM  Traceback (most recent call last):
Jun 5 04:55:28 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
Jun 5 04:55:28 PM      response = self.full_dispatch_request()
Jun 5 04:55:28 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
Jun 5 04:55:28 PM      rv = self.handle_user_exception(e)
Jun 5 04:55:28 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
Jun 5 04:55:28 PM      rv = self.dispatch_request()
Jun 5 04:55:28 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
Jun 5 04:55:28 PM      return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
Jun 5 04:55:28 PM    File "/opt/render/project/src/index.py", line 253, in demo2
Jun 5 04:55:28 PM      video.write_videofile('static/'+str(session['job'])+'.mp4', fps=24, audio_codec="aac", audio_bitrate="192k")
Jun 5 04:55:28 PM    File "<decorator-gen-55>", line 2, in write_videofile
Jun 5 04:55:28 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/moviepy/decorators.py", line 54, in requires_duration
Jun 5 04:55:28 PM      return f(clip, *a, **k)
Jun 5 04:55:28 PM    File "<decorator-gen-54>", line 2, in write_videofile
Jun 5 04:55:28 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/moviepy/decorators.py", line 135, in use_clip_fps_by_default
Jun 5 04:55:28 PM      return f(clip, *new_a, **new_kw)
Jun 5 04:55:28 PM    File "<decorator-gen-53>", line 2, in write_videofile
Jun 5 04:55:28 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/moviepy/decorators.py", line 22, in convert_masks_to_RGB
Jun 5 04:55:28 PM      return f(clip, *a, **k)
Jun 5 04:55:28 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/moviepy/video/VideoClip.py", line 300, in write_videofile
Jun 5 04:55:28 PM      ffmpeg_write_video(self, filename, fps, codec,
Jun 5 04:55:28 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/moviepy/video/io/ffmpeg_writer.py", line 228, in ffmpeg_write_video
Jun 5 04:55:28 PM      writer.write_frame(frame)
Jun 5 04:55:28 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/moviepy/video/io/ffmpeg_writer.py", line 180, in write_frame
Jun 5 04:55:28 PM      raise IOError(error)
Jun 5 04:55:28 PM  OSError: [Errno 32] Broken pipe
Jun 5 04:55:28 PM  
Jun 5 04:55:28 PM  MoviePy error: FFMPEG encountered the following error while writing file static/3.mp4:
Jun 5 04:55:28 PM  
Jun 5 04:55:28 PM   b''
```

**Comment by keikoro** [comment] 2023-06-20 23:55
Closing this issue as it's missing information we request when creating new issues: specs like MoviePy version, platform used etc. and/or useful code samples for reproducability and/or complete logs for errors where applicable (code-formatted text only, no screenshots).

We can reopen the issue once you've updated it. Please be aware you should always try to work with the latest master of MoviePy where possible, not the last PyPI release, which is quite old.

**Closed by keikoro** 2023-06-20 23:55 UTC
Labels: bug

**Comment by opc241** [comment] 2023-06-21 08:46
What else (to my given) informations do you need?

**Comment by Cinemagine** [comment] 2023-06-21 08:48
Hi,

I have managed to resolve the issue by upgrading my plan on render.com (http://render.com), so I suspect it was occurring due to limited system resources - thanks for getting back to me :)

Cheers

Lucas

--

**Comment by keikoro** [comment] 2023-06-21 14:28
> What else (to my given) informations do you need?

Please see my earlier comment. It only includes a small number of options (3).
