### ISSUE TITLE
myclip.write_videofile("movie.webm",audio=False) TypeError: must be real number, not NoneType

### ISSUE THREAD

**Issue by KhawajaAli** [Zulko/moviepy#1615] opened 2021-06-05 16:29 UTC
#### Expected Behavior
File should be exported without any issue

#### Actual Behavior
chunk:   0%|          | 0/152 [00:00<?, ?it/s, now=None]
Moviepy - Building video movie.webm.
MoviePy - Writing audio in movieTEMP_MPY_wvf_snd.ogg
                                                                   
MoviePy - Done.
Moviepy - Writing video movie.webm

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-22-dd7c1f8ed18c> in <module>
----> 1 myclip.write_videofile("movie.webm",audio=False)

~\anaconda3\envs\deep-music-visualizer\lib\site-packages\decorator.py in fun(*args, **kw)
    230             if not kwsyntax:
    231                 args, kw = fix(args, kw, sig)
--> 232             return caller(func, *(extras + args), **kw)
    233     fun.__name__ = func.__name__
    234     fun.__doc__ = func.__doc__

~\anaconda3\envs\deep-music-visualizer\lib\site-packages\moviepy\decorators.py in requires_duration(f, clip, *a, **k)
     52         raise ValueError("Attribute 'duration' not set")
     53     else:
---> 54         return f(clip, *a, **k)
     55 
     56 

~\anaconda3\envs\deep-music-visualizer\lib\site-packages\decorator.py in fun(*args, **kw)
    230             if not kwsyntax:
    231                 args, kw = fix(args, kw, sig)
--> 232             return caller(func, *(extras + args), **kw)
    233     fun.__name__ = func.__name__
    234     fun.__doc__ = func.__doc__

~\anaconda3\envs\deep-music-visualizer\lib\site-packages\moviepy\decorators.py in use_clip_fps_by_default(f, clip, *a, **k)
    133              for (k,v) in k.items()}
    134 
--> 135     return f(clip, *new_a, **new_kw)

~\anaconda3\envs\deep-music-visualizer\lib\site-packages\decorator.py in fun(*args, **kw)
    230             if not kwsyntax:
    231                 args, kw = fix(args, kw, sig)
--> 232             return caller(func, *(extras + args), **kw)
    233     fun.__name__ = func.__name__
    234     fun.__doc__ = func.__doc__

~\anaconda3\envs\deep-music-visualizer\lib\site-packages\moviepy\decorators.py in convert_masks_to_RGB(f, clip, *a, **k)
     20     if clip.ismask:
     21         clip = clip.to_RGB()
---> 22     return f(clip, *a, **k)
     23 
     24 @decorator.decorator

~\anaconda3\envs\deep-music-visualizer\lib\site-packages\moviepy\video\VideoClip.py in write_videofile(self, filename, fps, codec, bitrate, audio, audio_fps, preset, audio_nbytes, audio_codec, audio_bitrate, audio_bufsize, temp_audiofile, rewrite_audio, remove_temp, write_logfile, verbose, threads, ffmpeg_params, logger)
    305                            verbose=verbose, threads=threads,
    306                            ffmpeg_params=ffmpeg_params,
--> 307                            logger=logger)
    308 
    309         if remove_temp and make_audio:

~\anaconda3\envs\deep-music-visualizer\lib\site-packages\moviepy\video\io\ffmpeg_writer.py in ffmpeg_write_video(clip, filename, fps, codec, bitrate, preset, withmask, write_logfile, audiofile, verbose, threads, ffmpeg_params, logger)
    214                                 preset=preset, bitrate=bitrate, logfile=logfile,
    215                                 audiofile=audiofile, threads=threads,
--> 216                                 ffmpeg_params=ffmpeg_params) as writer:
    217 
    218         nframes = int(clip.duration*fps)

~\anaconda3\envs\deep-music-visualizer\lib\site-packages\moviepy\video\io\ffmpeg_writer.py in __init__(self, filename, size, fps, codec, audiofile, preset, bitrate, withmask, logfile, threads, ffmpeg_params)
     86             '-s', '%dx%d' % (size[0], size[1]),
     87             '-pix_fmt', 'rgba' if withmask else 'rgb24',
---> 88             '-r', '%.02f' % fps,
     89             '-an', '-i', '-'
     90         ]

TypeError: must be real number, not NoneType

#### Steps to Reproduce the Problem

```
from moviepy.editor import VideoFileClip
myclip = VideoFileClip("D:\Captures\Zoom Meeting.mp4")
myclip.write_videofile("movie.webm",audio=False)
```

#### Specifications

  - Python Version: 3.7.10
  - Moviepy Version: 1.0.3
  - Platform Name: Jupyter, windows
  - Platform Version:

**Comment by mondeja** [comment] 2021-06-06 10:58
Duplicate of #1614

**Closed** 2021-06-06 10:57 UTC
Labels: bug
