### ISSUE TITLE
The length of resulting audio is always double to the duration of the actual clip

### ISSUE THREAD

**Issue by chfw** [Zulko/moviepy#849] opened 2018-09-08 15:17 UTC
from moviepy.editor import AudioFileClip
    clip = AudioFileClip("my_video.webm")
    clip = clip.subclip(t_start=(0, 2, 0), t_end=(0, 2, 45))
    clip.write_audiofile('my.mp3')

[my_video.webm.gz](https://github.com/Zulko/moviepy/files/2363422/my_video.webm.gz)

### Expected Behavior

my.mp3 is of 45 seconds long

### Actual Behavior

my.mp3 is of 1 minute 30 seconds

### Steps to Reproduce the Problem

Please run above script

### Specifications

  - Python Version: python 3.6
  - Moviepy Version: 0.2.3.5
  - Platform Name: macos
  - Platform Version: 10.13.6

**Comment by maceurt** [comment] 2018-10-13 17:07
I tested it on ubuntu 16.04 and it worked fine for me. my.mp3 was 45 seconds long as expected. It might be a specific issue with moviepy on MacOS.

**Comment by keikoro** [comment] 2022-01-14 16:39
I'm closing this as the issue is very old and the problem couldn't be reproduced (on a different platform) back then.

Please open a new issue following the issue template if you're still experiencing the problem today with the latest recommended version of MoviePy.

**Closed by keikoro** 2022-01-14 16:39 UTC
Labels: bug, audio
