### ISSUE TITLE
Attempt to Download freeimage failing

### ISSUE THREAD

**Issue by virtualbrown** [Zulko/moviepy#111] opened 2014-12-31 00:05 UTC
Installed Moviepy on Mac.
Try to run the first time and the download of free image is failing.

Exception Type: IOError at /
Exception Value: Error while fetching file https://github.com/imageio/imageio-binaries/raw/master/freeimage/libfreeimage-3.16.0-osx10.6.dylib.
Dataset fetching aborted (**init**() got an unexpected keyword argument 'context')

**Comment by almarklein** [comment] 2015-01-02 22:12
Interesting. That last line in fetching.py actually catches an error and reraises  it. I would very much like to know the original source. Can you try commenting the lines in imageio/core/fetching.py where the catching is done (in `_fetch_file`)? Or maybe find out the real source via debugging?

**Comment by virtualbrown** [comment] 2015-01-15 06:20
Sorry just now getting back to this.  I traced this down in to urllb2.py.


class HTTPHandler(AbstractHTTPHandler):

    def http_open(self, req):
        return self.do_open(httplib.HTTPConnection, req)

    http_request = AbstractHTTPHandler.do_request_

if hasattr(httplib, 'HTTPS'):
    class HTTPSHandler(AbstractHTTPHandler):

        def __init__(self, debuglevel=0, context=None):
            AbstractHTTPHandler.__init__(self, debuglevel)
            self._context = context

        def https_open(self, req):
            return self.do_open(httplib.HTTPSConnection, req,
                context=self._context)    <---- this is failing.  _context is None.  See do_open below.

-----------------

 def do_open(self, http_class, req, **http_conn_args):
        """Return an addinfourl object for the request, using http_class.

        http_class must implement the HTTPConnection API from httplib.
        The addinfourl return value is a file-like object.  It also
        has methods and attributes including:
            - info(): return a mimetools.Message object for the headers
            - geturl(): return the original request URL
            - code: HTTP status code
        """
        host = req.get_host()
        if not host:
            raise URLError('no host given')

        # will parse host:port
        h = http_class(host, timeout=req.timeout, **http_conn_args)    <--- this is where the exception is thrown.


**http_conn_args is a dictionary containing

{'context': None}



LMK if you need more.  I'm not familiar enough with urllib to really understand what is going on there.

**Comment by almarklein** [comment] 2015-01-15 09:52
From a brief look, I think this may be related to certificates. Can you please try changing `https://` into `http://` (i.e. remove the "s") in:

    `_url_root = 'https://github.com/imageio/imageio-binaries/raw/master/'

in fetching.py (line 47 in master).

**Comment by virtualbrown** [comment] 2015-01-15 15:30
Hi.

I made the change but still get the same error.

Exception Type: IOError at /
Exception Value: Error while fetching file http://github.com/imageio/imageio-binaries/raw/master/freeimage/libfreeimage-3.16.0-osx10.6.dylib.
Dataset fetching aborted (__init__() got an unexpected keyword argument 'context')

**Comment by virtualbrown** [comment] 2015-01-16 05:22
I made the following change in urllib2.py line 1166 and it worked.
At least this got the library to install.

 def do_open(self, http_class, req, **http_conn_args):
        """Return an addinfourl object for the request, using http_class.

        http_class must implement the HTTPConnection API from httplib.
        The addinfourl return value is a file-like object.  It also
        has methods and attributes including:
            - info(): return a mimetools.Message object for the headers
            - geturl(): return the original request URL
            - code: HTTP status code
        """
        host = req.get_host()
        if not host:
            raise URLError('no host given')

        # will parse host:port
        #h = http_class(host, timeout=req.timeout, **http_conn_args)    <--- commented this out.
        h = http_class(host, timeout=req.timeout)

**Comment by almarklein** [comment] 2015-01-17 21:07
Changing your urllib2.py file is not a very nice solution; it might break other code. Are you sure the `http` thing did not work? Because if you look at the code for `http_open` vs `https_open` you see the `http` version omits the context argument, which seems to be triggering the problem.

To be absolutely sure could you try just calling:

    path = 'imageio/imageio-binaries/raw/master/freeimage/libfreeimage-3.16.0-osx10.6.dylib'
    urlopen('https://github.com/' + path)  # should fail
    urlopen('http://github.com/' + path)  # I hope this works

**Comment by virtualbrown** [comment] 2015-01-17 22:28
I tried that code and the http call fails as well with the following error.

__init__() got an unexpected keyword argument 'context' (<type 'exceptions.TypeError'>)

I'm pretty new to Python is it possible that I have incompatible libraries (based on version) somehow?


Also, regarding my tweak of urllib2, after I was able to download the file...I changed it back. I just needed a way to get around the download.

**Comment by almarklein** [comment] 2015-01-17 23:02
I am not sure about the cause. It seems rather specific to your system. I was hoping we could find a way to change imageio to avoid the error, but it seems this is not possible.

I am glad you solved your problem. Let's hope your case was a rare exception.

**Comment by Zulko** [comment] 2015-01-17 23:07
I'm leaving the issue open just in case someone else has the same problem.

**Comment by kerstin** [comment] 2017-02-18 20:40
I'm closing this issue as it sounds like OP solved their problem and 2+ years later, no-one else has commented to have run into the same problem.

**Closed by kerstin** 2017-02-18 20:40 UTC
