### ISSUE TITLE
Switch from ffmpeg to ffprobe for video info

### ISSUE THREAD

**Issue by teknogeek** [Zulko/moviepy#590] opened 2017-06-18 01:11 UTC
First, some formalities.

**Python Version:** 2.7.10 in a virtualenv
**Host OS:** macOS 10.12.5
**FFMPEG Version:** 3.3.2

Okay, now that that's out of the way...

I am currently attempting to run MoviePy to load up a video using the following code:
```python
from moviepy.editor import *
video = VideoFileClip('test.mp4')
```
However, it hangs regardless of the video and I always end up cancelling it with CTRL+C. After some investigating, I have finally figured out what is causing the issue. MoviePy attempts to read from `stdout` when executing the base command `ffmpeg -i <file name>` with `subprocess`. The problem with this is that `ffmpeg` requires an output file be specified as can be seen in the output from manual execution of the command:

```
→ ffmpeg -i test.mp4
ffmpeg version 3.3.2 Copyright (c) 2000-2017 the FFmpeg developers
  built with Apple LLVM version 8.1.0 (clang-802.0.42)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.3.2 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --disable-lzma --enable-vda
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'test.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2015-11-22T15:03:04.000000Z
  Duration: 00:00:10.94, start: 0.000000, bitrate: 3198 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 3003 kb/s, 30 fps, 30 tbr, 30 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 192 kb/s (default)
    Metadata:
      creation_time   : 2015-11-22T15:03:05.000000Z
      handler_name    : IsoMedia File Produced by Google, 5-11-2011
At least one output file must be specified
```

As a result, attempting to read from `stdout` will cause the program to hang because there is no output to stdout, only `stderr`. To keep using `ffmpeg` for this, you would need to read from `stderr` instead which would quite frankly be very jenky. Instead, I propose using `ffprobe` in order to read the information about the file and parse it directly from JSON. This would make things quite a bit simpler and much cleaner anyways.

You can get the information from a file with `ffprobe` like this:
```
→ ffprobe -v quiet -print_format json -show_format -show_streams -print_format json test.mp4
{
    "streams": [
        {
            "index": 0,
            "codec_name": "h264",
            "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
            "profile": "High",
            "codec_type": "video",
            "codec_time_base": "1/60",
            "codec_tag_string": "avc1",
            "codec_tag": "0x31637661",
            "width": 1280,
            "height": 720,
            "coded_width": 1280,
            "coded_height": 720,
            "has_b_frames": 0,
            "sample_aspect_ratio": "1:1",
            "display_aspect_ratio": "16:9",
            "pix_fmt": "yuv420p",
            "level": 31,
            "chroma_location": "left",
            "refs": 1,
            "is_avc": "true",
            "nal_length_size": "4",
            "r_frame_rate": "30/1",
            "avg_frame_rate": "30/1",
            "time_base": "1/30",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 328,
            "duration": "10.933333",
            "bit_rate": "3003098",
            "bits_per_raw_sample": "8",
            "nb_frames": "328",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "language": "und",
                "handler_name": "VideoHandler"
            }
        },
        {
            "index": 1,
            "codec_name": "aac",
            "codec_long_name": "AAC (Advanced Audio Coding)",
            "profile": "LC",
            "codec_type": "audio",
            "codec_time_base": "1/44100",
            "codec_tag_string": "mp4a",
            "codec_tag": "0x6134706d",
            "sample_fmt": "fltp",
            "sample_rate": "44100",
            "channels": 2,
            "channel_layout": "stereo",
            "bits_per_sample": 0,
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/44100",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 482304,
            "duration": "10.936599",
            "bit_rate": "192087",
            "max_bit_rate": "202136",
            "nb_frames": "471",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "creation_time": "2015-11-22T15:03:05.000000Z",
                "language": "eng",
                "handler_name": "IsoMedia File Produced by Google, 5-11-2011"
            }
        }
    ],
    "format": {
        "filename": "test.mp4",
        "nb_streams": 2,
        "nb_programs": 0,
        "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
        "format_long_name": "QuickTime / MOV",
        "start_time": "0.000000",
        "duration": "10.935000",
        "size": "4371780",
        "bit_rate": "3198375",
        "probe_score": 100,
        "tags": {
            "major_brand": "mp42",
            "minor_version": "0",
            "compatible_brands": "isommp42",
            "creation_time": "2015-11-22T15:03:04.000000Z"
        }
    }
}
```

I am open to suggestions to this and would be more than happy to make a pull request when I find some time if someone else doesn't, but this is just my 2¢ regarding this. Thanks!

**Comment by Zulko** [comment] 2017-06-18 08:09
Just to make sure I understand: the problem is not when reading the video, but when reading the infos on the video right ? The problem on moviepy's side would be that up to ffmpeg2, the output was put in stdout, while with ffmpeg3 it goes to stderr (?), which would be why you get that hanging problem (which I have never seen before).

I'm not sure I got it right, but if that is the problem, the solution would be to launch the ffmpeg "infos" command with stderr and stdout, then parse whichever contains something, this way it would work with ffmpeg2 and ffmpeg3

I want to avoid ffprobe as much as possible because it is one more download.

**Comment by mrname** [comment] 2017-12-19 20:13
Any suggestions for working around this for now?

**Comment by thenewguy** [comment] 2019-11-09 00:37
related https://github.com/Zulko/moviepy/issues/249

**Comment by keikoro** [comment] 2022-10-11 01:11
Closing this issue as it's old and hasn't seen any (further) response from OP in several years.

**Closed by keikoro** 2022-10-11 01:11 UTC
Labels: lib-FFmpeg
