### ISSUE TITLE
Pillow version 10 error in resizing video

### ISSUE THREAD

**Issue by alimirjahani7** [Zulko/moviepy#2057] opened 2023-10-21 13:34 UTC
#### Expected Behavior
generate a video with reduced size

#### Actual Behavior
raise exception AttributeError("module 'PIL.Image' has no attribute 'ANTIALIAS'")
--

#### Steps to Reproduce the Problem
install pillow version 10

#### Specifications
looks like pillow version 10 removed the support for ANTIALIAS
https://stackoverflow.com/questions/76616042/attributeerror-module-pil-image-has-no-attribute-antialias

**Comment by Goyet-Christopher** [comment] 2023-10-22 04:35
Already fix (issue #2002) by the pull request #2003. 
(https://github.com/Zulko/moviepy/pull/2003 but I'm not sure in which version of MoviePy this has been fixed)

File moviepy/video/fx/resize.py:
        resized_pil = pil_img.resize(new_size[::-1], Image.ANTIALIAS) 
 was replaced by :
        resized_pil = pil_img.resize(new_size[::-1], Image.LANCZOS)
        
Hoping that I have been helpful ;)

**Comment by alimirjahani7** [comment] 2023-10-22 12:41
Thanks
but I checked and faced this error in the latest version of moviepy

**Comment by PetroTruman** [comment] 2023-10-23 13:00
I had same problem. I fixed it jast  installing **opencv-python**  it works for me.
because Movipy use external moduls for _resize_ function.
a find answer hear https://github.com/Zulko/moviepy/issues/2002

**Comment by Kaszanas** [comment] 2023-10-23 15:01
> Already fix (issue #2002) by the pull request #2003. (#2003 but I'm not sure in which version of MoviePy this has been fixed)
> 
> File moviepy/video/fx/resize.py: resized_pil = pil_img.resize(new_size[::-1], Image.ANTIALIAS) was replaced by : resized_pil = pil_img.resize(new_size[::-1], Image.LANCZOS)
> 
> Hoping that I have been helpful ;)

Latest release of moviepy is 1.0.3, and it is from May 7 2020, hence any of the fixes that have been made are unlikely to be live on PyPI. It would be a good idea to have one of the fixed versions released on PyPI for everyone to use.

**Comment by Kaszanas** [comment] 2023-10-23 18:41
> Another repo with update code which don't release any more :/(

I think that unfortunately that is true. Most of the functionality is still there though. I think there is a PR that aims to be a 2.0 release of moviepy. I am not sure who is a contributor that could make the decision to include the changes and go forward with all of this.

**Comment by keikoro** [comment] 2024-02-10 19:41
Closing this as duplicate of #2072, which seems to be the only ticket referencing the library's actual release notes.

**Closed by keikoro** 2024-02-10 19:41 UTC
Labels: bug, images, lib-PIL-Pillow
