### ISSUE TITLE
On windows, a preview doesn't close when you quit.

### ISSUE THREAD

**Issue by mgrazebrook** [Zulko/moviepy#575] opened 2017-05-31 17:00 UTC
I'm using windows, Python 3.6 and moviepy 0.2.3.2, run through jupyter notebook.

clip.ipython_display() runs but doesn't produce any visible result.

clip.preview() pops up a PyGame window. The command ends on ESC. But the window doesn't pop down. I can close it by importing pygame and calling pygame.quit()

**Comment by mondeja** [comment] 2021-04-15 08:11
The `clip.preview()` problem has been successfully fixed in #575.

**Comment by mondeja** [comment] 2021-04-15 08:38
> clip.ipython_display() runs but doesn't produce any visible result.

I can't reproduce this problem with moviepy *master* and latest Jupyter Notebook version (`notebook==6.3.0`). Given the age of the report, it is likely that it has been fixed or is no longer a problem with current dependencies. I'm closing this, if someones can reproduce it, please report it here and we'll investigate again.

**Closed by mondeja** 2021-04-15 08:38 UTC
Labels: bug, pygame

**Comment by mgrazebrook** [comment] 2021-09-30 09:55
Thanks.
