### ISSUE TITLE
ImageSequenceClip from OpenEXR file sequence generate black Clip video

### ISSUE THREAD

**Issue by maty974** [Zulko/moviepy#186] opened 2015-07-15 13:28 UTC
Hi,

I'm trying to generate a video file from an OpenEXR image file sequence,
the video file generated match the input file sequence resolution, fps, duration but it is entire Black

Here is the code I use to generate the movie file:

``` python
clip1 = ImageSequenceClip('/path_to/exr', fps=24)
params = [
       '-b:v', '34000K', '-q:v', '2', '-qmin', '1', '-vf', 'scale=1280:960'
       ]
clip1.write_videofile("/path_to_movie/from_exr_images_sequence_1280x960.mov", 
                        codec='mjpeg', 
                        threads=16, 
                        write_logfile=True, 
                        ffmpeg_params=params,
                        verbose=True)
```

And here is the output of ImageMagick identify command of one image file:

```
Image: /path_to/bg_0101.exr
  Format: EXR (High Dynamic-range (HDR))
  Class: DirectClass
  Geometry: 2578x1080+0+0
  Resolution: 72x72
  Print size: 35.8056x15
  Units: Undefined
  Type: TrueColorMatte
  Endianess: Undefined
  Colorspace: sRGB
  Depth: 16-bit
  Channel depth:
    red: 16-bit
    green: 16-bit
    blue: 16-bit
    alpha: 1-bit
  Channel statistics:
    Red:
      min: 0 (0)
      max: 24832 (0.378912)
      mean: 3346.79 (0.0510688)
      standard deviation: 3678.74 (0.056134)
      kurtosis: 0.655223
      skewness: 0.941868
    Green:
      min: 0 (0)
      max: 25504 (0.389166)
      mean: 4941.01 (0.075395)
      standard deviation: 5068.28 (0.077337)
      kurtosis: -0.763445
      skewness: 0.517146
    Blue:
      min: 0 (0)
      max: 25728 (0.392584)
      mean: 5718.85 (0.087264)
      standard deviation: 5715.65 (0.0872153)
      kurtosis: -1.19134
      skewness: 0.353031
    Alpha:
      min: 65535 (1)
      max: 65535 (1)
      mean: 65535 (1)
      standard deviation: 0 (0)
      kurtosis: 0
      skewness: 0
  Image statistics:
    Overall:
      min: 0 (0)
      max: 25728 (0.392584)
      mean: 3501.66 (0.053432)
      standard deviation: 4239.38 (0.0646888)
      kurtosis: 2.01722
      skewness: 1.55204
  Rendering intent: Perceptual
  Gamma: 0.45455
  Chromaticity:
    red primary: (0.64,0.33)
    green primary: (0.3,0.6)
    blue primary: (0.15,0.06)
    white point: (0.3127,0.329)
  Interlace: None
  Background color: white
  Border color: srgba(223,223,223,1)
  Matte color: grey74
  Transparent color: none
  Compose: Over
  Page geometry: 2578x1080+0+0
  Dispose: Undefined
  Iterations: 0
  Compression: Undefined
  Orientation: Undefined
  Properties:
    date:create: 2015-07-13T17:30:17+02:00
    date:modify: 2015-07-13T17:30:17+02:00
    signature: d87bc0caedb299d07355306fc8f5fc4d0104b4fdc606a7eaffd96b5150fe5cbb
  Artifacts:
    verbose: true
  Tainted: False
  Filesize: 3.725MB
  Number pixels: 2.784M
  Pixels per second: 15.47MB
  User time: 0.150u
  Elapsed time: 0:01.180
  Version: ImageMagick 6.7.5-6 2012-08-11 Q16 http://www.imagemagick.org
```

Thanks for your help

**Comment by maty974** [comment] 2015-07-15 13:33
I've also tested with ImageIO module to see if it can Read/Write the image file, and it's working fine

```python
im = imageio.imread('/path_to_exr/bg_0101.exr')
imageio.imwrite("/path_to_output/exr_frame_from_imageio.png", im)
```

Maybe something about image data is lost in the ImageSequenceClip code ?

**Comment by Zulko** [comment] 2015-07-15 13:38
MoviePy's ImageSequenceClip cannot read ".exr" files. At this point I would say that the best is to go with imageio to make the video. Unless you want to do something else (like adding a title, compositing, etc.) a which case I can suggest some solutions to make it work with MoviePy (still using imageio to read the exr).

**Comment by maty974** [comment] 2015-07-15 15:58
But what I see from the ImageSequenceClip source code, is that it's using imageio to read the image sequence files no ?

Anyway, yes the idea is to use some features of MoviePy to add text etc... in the generated movie file,
your help is welcome :)

Thanks for your quick response

**Comment by Zulko** [comment] 2015-07-15 21:36
Oh I misread your first message. Have you tried with basic settings, like just `clip1.write_videofile("test.mp4")` ?

**Comment by maty974** [comment] 2015-07-16 09:17
Tested with `clip1.write_videofile("test.mp4")` produce the same result, video image completely black.

I've also test by adding TextClip on the sequence image source and I can see only the Text in the video output file.

**Comment by Zulko** [comment] 2015-07-16 10:27
Can you send me some assets to reproduce the bug (e.g. 2 images + code)

**Comment by maty974** [comment] 2015-07-16 13:15
Sure here are a sequence exr file of 3 frames

http://we.tl/tGnSzgtNta

The code used to generate movie file

```python
clip1 = ImageSequenceClip('/path_to/exr', fps=24)
params = [
       '-b:v', '34000K', '-q:v', '2', '-qmin', '1', '-vf', 'scale=1280:960'
       ]
clip1.write_videofile("/path_to_movie/from_exr_images_sequence_1280x960.mov", 
                        codec='mjpeg', 
                        threads=16, 
                        write_logfile=True, 
                        ffmpeg_params=params,
                        verbose=True)
```

**Comment by Zulko** [comment] 2015-07-16 14:15
The issue is that ImageIO returns an image where colors are encoded between 0 and 1 instead of the 0-255 expected by moviepy. A quick solution is to reencode the colors. This should work:

    def make_uint8(im):
        return (255*im).astype('uint8')

    clip1 = ImageSequenceClip('./exr', fps=1).fl_image(make_uint8)
    # then the rest of your code

**Comment by maty974** [comment] 2015-07-16 15:44
Awesome :) it is working now !

PS: is there any colorspace conversion feature in MoviePy ? because I forgot to mention
that the input EXR image are in Linear colorspace, and the output movie must be in sRGB

Thanks a lot for your help.

**Comment by Zulko** [comment] 2015-07-16 16:09
Just get one function from scikit-image and apply it using fl_image() like in my previous example.

**Comment by maty974** [comment] 2015-07-17 09:58
Ok, thanks again @Zulko

**Comment by kerstin** [comment] 2017-02-18 00:03
Looks like the original issue was solved + additional questions were answered. Closing.

**Closed by kerstin** 2017-02-18 00:03 UTC
