### ISSUE TITLE
This error can be due to the fact that ImageMagick is not installed on your computer, or (for Windows users) that you didn't specify the path to the ImageMagick binary in file conf.py, or that the path you specified is incorrect

### ISSUE THREAD

**Issue by adnanhassan23** [Zulko/moviepy#1966] opened 2023-05-05 21:40 UTC
My code is working fine on local machine but when i deploy on gcloud app engine getting above error. here's my dockerfile

```
FROM python:3.8-slim

# Install ImageMagick
RUN apt-get update && \
    apt-get install -y imagemagick

# Update ImageMagick policy.xml
RUN sed -i 's/rights="none" pattern="PDF"/rights="read|write" pattern="PDF"/' /etc/ImageMagick-6/policy.xml

# Install FFmpeg
RUN apt-get update && \
    apt-get install -y ffmpeg

# Install build-essential for uWSGI
RUN apt-get update && \
    apt-get install -y build-essential

# Install Python dependencies
COPY requirements.txt /app/
RUN pip install -r /app/requirements.txt

# Copy your application files
COPY . /app/

# Set the working directory
WORKDIR /app

CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 main:app
```
Logs
```
2023-05-05 21:37:49 default[20230506t022600]  [2023-05-05 21:37:49,818] ERROR in app: Exception on / [POST]
2023-05-05 21:37:49 default[20230506t022600]  Traceback (most recent call last):    File "/usr/local/lib/python3.8/site-packages/moviepy/video/VideoClip.py", line 1137, in __init__      subprocess_call(cmd, logger=None)    File "/usr/local/lib/python3.8/site-packages/moviepy/tools.py", line 54, in subprocess_call      raise IOError(err.decode('utf8'))  OSError: convert-im6.q16: 
attempt to perform an operation not allowed by the security policy `@/tmp/tmpiyc0_r56.txt' @ error/property.c/InterpretImageProperties/3706.
2023-05-05 21:37:49 default[20230506t022600]  convert-im6.q16: no images defined `PNG32:/tmp/tmp5nj8s4bi.png' @ error/convert.c/ConvertImageCommand/3229.
2023-05-05 21:37:49 default[20230506t022600]
2023-05-05 21:37:49 default[20230506t022600]
2023-05-05 21:37:49 default[20230506t022600]  During handling of the above exception, another exception occurred:
2023-05-05 21:37:49 default[20230506t022600]
2023-05-05 21:37:49 default[20230506t022600]  Traceback (most recent call last):    File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app      response = self.full_dispatch_request()    File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request      rv = self.handle_user_exception(e)    File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request      rv = self.dispatch_request()    File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request      return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)    File "/app/main.py", line 60, in adnan      text = TextClip(    File "/usr/local/lib/python3.8/site-packages/moviepy/video/VideoClip.py", line 1146, in __init__      raise IOError(error)  OSError: MoviePy Error: creation of None failed because of the following error:
2023-05-05 21:37:49 default[20230506t022600]
2023-05-05 21:37:49 default[20230506t022600]  convert-im6.q16: attempt to perform an operation not allowed by the security policy `@/tmp/tmpiyc0_r56.txt' @ error/property.c/InterpretImageProperties/3706.
2023-05-05 21:37:49 default[20230506t022600]  convert-im6.q16: no images defined `PNG32:/tmp/tmp5nj8s4bi.png' @ error/convert.c/ConvertImageCommand/3229.
2023-05-05 21:37:49 default[20230506t022600]  .
2023-05-05 21:37:49 default[20230506t022600]
2023-05-05 21:37:49 default[20230506t022600]  .This error can be due to the fact that ImageMagick is not installed on your computer, or (for Windows users) that you didn't specify the path to the ImageMagick binary in file conf.py, or that the path you specified is incorrect

```

please let me know how can i fix this error

**Comment by LHKode** [comment] 2023-05-12 02:36
Hi, 
I have the same error. And I have checked all the thing (the ImageMagick path, policy.xml file). Everything is fine. The only problem I met is **the text** I want to insert is **empty**. haaa, how stupid I am 
Hope this help you in some way!!!

**Comment by keikoro** [comment] 2023-06-20 23:52
Closing this issue as it's missing information we request when creating new issues: specs like MoviePy version, platform used etc. and/or useful code samples for reproducability and/or complete logs for errors where applicable (code-formatted text only, no screenshots).

We can reopen the issue once you've updated it. Please be aware you should always try to work with the latest master of MoviePy where possible, not the last PyPI release, which is quite old.

**Closed by keikoro** 2023-06-20 23:52 UTC
Labels: question

**Comment by barteshwar** [comment] 2023-07-05 20:16
I have the exact same issue. The app works fine on my local machine, but I get this error when deploying on Streamlit. Does anyone have a solution?

**Comment by adnanhassan23** [comment] 2023-07-05 21:14
Hi Guys,

i fixed the issue with docker. here's dockerfile code


```

FROM python:3.11

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

RUN apt-get update \
    && apt-get install -qq -y build-essential xvfb xdg-utils wget unzip ffmpeg libpq-dev vim libmagick++-dev fonts-liberation sox bc gsfonts --no-install-recommends\
    && apt-get clean

## ImageMagicK Installation 
RUN mkdir -p /tmp/distr && \
    cd /tmp/distr && \
    wget https://download.imagemagick.org/ImageMagick/download/releases/ImageMagick-7.0.11-2.tar.xz && \
    tar xvf ImageMagick-7.0.11-2.tar.xz && \
    cd ImageMagick-7.0.11-2 && \
    ./configure --enable-shared=yes --disable-static --without-perl && \
    make && \
    make install && \
    ldconfig /usr/local/lib && \
    cd /tmp && \
    rm -rf distr

COPY . .

CMD [ "python", "-u", "app.py"]

```

**Comment by AlexAdamov** [comment] 2023-07-26 16:03
I have the same issue. My code works fine on my mac dev machine but when I deploy to Digital Ocean, I have this error.

moviepy==1.0.3

Plaform: Debian GNU/Linux 12 (bookworm)
ffmpeg version 5.1.3-1
ImageMagick 7.0.11-2 Q16 x86_64 2021-02-27

Code sample: Creating still image clips and concatenating them

`    sample_image = ImageSequenceClip([os.path.join(images_folder, images[0])], durations=[1])
    video_height = sample_image.size[1]
    video_width = sample_image.size[0]
    for i, img in enumerate(images):
        img_path = os.path.join(images_folder, img)
        logger.debug(f"Image path: {img_path}")
        scene_number = int(img.split('.')[0])
        scene_info = scenes_df[scenes_df['scene_number'] == scene_number]
        # For the first image, set start_time to 0
        try:
            if i == 0:
                start_time = 0
            else:
                start_time = scene_info['timestamp'].item()

            # Determine end time based on whether it's the last image
            if i != len(images) - 1:
                logger.debug("line10")
                end_time = scenes_df.loc[scenes_df['scene_number'] == int(images[i + 1].split('.')[0]), 'timestamp'].item()
            else:
                end_time = scene_info['segment_end_time'].item()

        except ValueError as e:
            logger.error(f"Error for image {img} with scene number {scene_number}")
            logger.error(f"Scene info DataFrame:\n{scene_info}")
            raise
        duration = end_time - start_time
        # Check if it's the last image and duration is less than 3 seconds
        if i == len(images) - 1 and duration < 3:
            # Extend the duration of the penultimate clip to the end of the transcript
            clips[-1] = clips[-1].set_duration(clips[-1].duration + duration)
            continue  # Skip this clip

        # Convert images to video clips
        logger.debug(f"clips {clips}")
        logger.debug(f"img_path {img_path}")
        logger.debug(f"duration: {duration}")
        try:
            img = Image.open(img_path)  # try to open the image
            img.verify()  # verify that it is, in fact, an image
            print(f"File {img_path} can be opened and is a valid image.")
        except (IOError, SyntaxError) as e:
            print(f"File {img_path} could not be opened or is not a valid image. Error: {e}")
        
        clip = ImageClip(img_path)
        clip = clip.set_duration(duration)
        # clip = ImageSequenceClip([img_path], durations=[duration])
        clips.append(clip)

    # Concatenate image clips
    final_clip = concatenate_videoclips(clips)`

Som logs:

`2023-07-26T12:37:30.527299060Z [2023-07-26 12:37:30,527: DEBUG/ForkPoolWorker-2] STREAM b'IHDR' 16 13
2023-07-26T12:37:30.527380119Z [2023-07-26 12:37:30,527: DEBUG/ForkPoolWorker-2] STREAM b'pHYs' 41 9
2023-07-26T12:37:30.527439957Z [2023-07-26 12:37:30,527: DEBUG/ForkPoolWorker-2] STREAM b'IDAT' 62 8192
2023-07-26T12:37:30.533743964Z [2023-07-26 12:37:30,533: WARNING/ForkPoolWorker-2] File temp_files/images/3bb51641-eea8-4b1a-97b7-8752de3b9443/8d7ce23a-283d-4042-9e1d-a1011da064f5/9.oESYLiLvL8g0nnKb1FVr.png can be opened and is a valid image.
2023-07-26T12:37:30.534140722Z [2023-07-26 12:37:30,533: DEBUG/ForkPoolWorker-2] STREAM b'IHDR' 16 13
2023-07-26T12:37:30.534213681Z [2023-07-26 12:37:30,534: DEBUG/ForkPoolWorker-2] STREAM b'pHYs' 41 9
2023-07-26T12:37:30.534324167Z [2023-07-26 12:37:30,534: DEBUG/ForkPoolWorker-2] STREAM b'IDAT' 62 8192
2023-07-26T12:37:30.534468476Z [2023-07-26 12:37:30,534: DEBUG/ForkPoolWorker-2] STREAM b'IHDR' 16 13
2023-07-26T12:37:30.534534756Z [2023-07-26 12:37:30,534: DEBUG/ForkPoolWorker-2] STREAM b'pHYs' 41 9
2023-07-26T12:37:30.534602764Z [2023-07-26 12:37:30,534: DEBUG/ForkPoolWorker-2] STREAM b'IDAT' 62 8192
2023-07-26T12:37:30.570083970Z [2023-07-26 12:37:30,569: DEBUG/ForkPoolWorker-2] Error closing: Operation on closed image
2023-07-26T12:37:30.570266185Z [2023-07-26 12:37:30,569: DEBUG/ForkPoolWorker-2] create_video_task[83a8784f-29c2-49b7-9562-5217cc183b11]: Image path: temp_files/images/3bb51641-eea8-4b1a-97b7-8752de3b9443/8d7ce23a-283d-4042-9e1d-a1011da064f5/10.lJyaPoXmnuBSoGfxz1aB.png
2023-07-26T12:37:30.571389271Z [2023-07-26 12:37:30,571: DEBUG/ForkPoolWorker-2] create_video_task[83a8784f-29c2-49b7-9562-5217cc183b11]: line10
2023-07-26T12:37:30.572141988Z [2023-07-26 12:37:30,571: DEBUG/ForkPoolWorker-2] create_video_task[83a8784f-29c2-49b7-9562-5217cc183b11]: clips [<moviepy.video.VideoClip.ImageClip object at 0x7f655ed14f10>, <moviepy.video.VideoClip.ImageClip object at 0x7f655ed173a0>, <moviepy.video.VideoClip.ImageClip object at 0x7f655ed15ed0>, <moviepy.video.VideoClip.ImageClip object at 0x7f655ed16590>, <moviepy.video.VideoClip.ImageClip object at 0x7f655ed16890>, <moviepy.video.VideoClip.ImageClip object at 0x7f655ed16f20>, <moviepy.video.VideoClip.ImageClip object at 0x7f655ed17e50>, <moviepy.video.VideoClip.ImageClip object at 0x7f655ed14b20>, <moviepy.video.VideoClip.ImageClip object at 0x7f655ed16e30>]
2023-07-26T12:37:30.572268164Z [2023-07-26 12:37:30,572: DEBUG/ForkPoolWorker-2] create_video_task[83a8784f-29c2-49b7-9562-5217cc183b11]: img_path temp_files/images/3bb51641-eea8-4b1a-97b7-8752de3b9443/8d7ce23a-283d-4042-9e1d-a1011da064f5/10.lJyaPoXmnuBSoGfxz1aB.png
2023-07-26T12:37:30.572371916Z [2023-07-26 12:37:30,572: DEBUG/ForkPoolWorker-2] create_video_task[83a8784f-29c2-49b7-9562-5217cc183b11]: duration: -4.0
2023-07-26T12:37:30.572637866Z [2023-07-26 12:37:30,572: DEBUG/ForkPoolWorker-2] STREAM b'IHDR' 16 13
2023-07-26T12:37:30.572791383Z [2023-07-26 12:37:30,572: DEBUG/ForkPoolWorker-2] STREAM b'pHYs' 41 9
2023-07-26T12:37:30.572800946Z [2023-07-26 12:37:30,572: DEBUG/ForkPoolWorker-2] STREAM b'IDAT' 62 8192
2023-07-26T12:37:30.577878971Z [2023-07-26 12:37:30,577: WARNING/ForkPoolWorker-2] File temp_files/images/3bb51641-eea8-4b1a-97b7-8752de3b9443/8d7ce23a-283d-4042-9e1d-a1011da064f5/10.lJyaPoXmnuBSoGfxz1aB.png can be opened and is a valid image.
2023-07-26T12:37:30.578301217Z [2023-07-26 12:37:30,578: DEBUG/ForkPoolWorker-2] STREAM b'IHDR' 16 13
2023-07-26T12:37:30.578392211Z [2023-07-26 12:37:30,578: DEBUG/ForkPoolWorker-2] STREAM b'pHYs' 41 9
2023-07-26T12:37:30.578468857Z [2023-07-26 12:37:30,578: DEBUG/ForkPoolWorker-2] STREAM b'IDAT' 62 8192
2023-07-26T12:37:30.578585831Z [2023-07-26 12:37:30,578: DEBUG/ForkPoolWorker-2] STREAM b'IHDR' 16 13
2023-07-26T12:37:30.578661916Z [2023-07-26 12:37:30,578: DEBUG/ForkPoolWorker-2] STREAM b'pHYs' 41 9
2023-07-26T12:37:30.578731737Z [2023-07-26 12:37:30,578: DEBUG/ForkPoolWorker-2] STREAM b'IDAT' 62 8192
2023-07-26T12:37:30.612708310Z [2023-07-26 12:37:30,612: DEBUG/ForkPoolWorker-2] Error closing: Operation on closed image
2023-07-26T12:37:30.612906998Z [2023-07-26 12:37:30,612: DEBUG/ForkPoolWorker-2] create_video_task[83a8784f-29c2-49b7-9562-5217cc183b11]: Image path: temp_files/images/3bb51641-eea8-4b1a-97b7-8752de3b9443/8d7ce23a-283d-4042-9e1d-a1011da064f5/11.xWRlMjRIwHwq2xWA0oGJ.png
2023-07-26T12:37:30.614345592Z [2023-07-26 12:37:30,613: DEBUG/ForkPoolWorker-2] create_video_task[83a8784f-29c2-49b7-9562-5217cc183b11]: clips [<moviepy.video.VideoClip.ImageClip object at 0x7f655ed14f10>, <moviepy.video.VideoClip.ImageClip object at 0x7f655ed173a0>, <moviepy.video.VideoClip.ImageClip object at 0x7f655ed15ed0>, <moviepy.video.VideoClip.ImageClip object at 0x7f655ed16590>, <moviepy.video.VideoClip.ImageClip object at 0x7f655ed16890>, <moviepy.video.VideoClip.ImageClip object at 0x7f655ed16f20>, <moviepy.video.VideoClip.ImageClip object at 0x7f655ed17e50>, <moviepy.video.VideoClip.ImageClip object at 0x7f655ed14b20>, <moviepy.video.VideoClip.ImageClip object at 0x7f655ed16e30>, <moviepy.video.VideoClip.ImageClip object at 0x7f655ed17ee0>]
2023-07-26T12:37:30.614417097Z [2023-07-26 12:37:30,614: DEBUG/ForkPoolWorker-2] create_video_task[83a8784f-29c2-49b7-9562-5217cc183b11]: img_path temp_files/images/3bb51641-eea8-4b1a-97b7-8752de3b9443/8d7ce23a-283d-4042-9e1d-a1011da064f5/11.xWRlMjRIwHwq2xWA0oGJ.png
2023-07-26T12:37:30.614424068Z [2023-07-26 12:37:30,614: DEBUG/ForkPoolWorker-2] create_video_task[83a8784f-29c2-49b7-9562-5217cc183b11]: duration: 13.344000000000001
2023-07-26T12:37:30.614599788Z [2023-07-26 12:37:30,614: DEBUG/ForkPoolWorker-2] STREAM b'IHDR' 16 13
2023-07-26T12:37:30.614706387Z [2023-07-26 12:37:30,614: DEBUG/ForkPoolWorker-2] STREAM b'pHYs' 41 9
2023-07-26T12:37:30.614807954Z [2023-07-26 12:37:30,614: DEBUG/ForkPoolWorker-2] STREAM b'IDAT' 62 8192
2023-07-26T12:37:30.619664704Z [2023-07-26 12:37:30,619: WARNING/ForkPoolWorker-2] File temp_files/images/3bb51641-eea8-4b1a-97b7-8752de3b9443/8d7ce23a-283d-4042-9e1d-a1011da064f5/11.xWRlMjRIwHwq2xWA0oGJ.png can be opened and is a valid image.
2023-07-26T12:37:30.620043674Z [2023-07-26 12:37:30,619: DEBUG/ForkPoolWorker-2] STREAM b'IHDR' 16 13
2023-07-26T12:37:30.620114500Z [2023-07-26 12:37:30,620: DEBUG/ForkPoolWorker-2] STREAM b'pHYs' 41 9
2023-07-26T12:37:30.620194426Z [2023-07-26 12:37:30,620: DEBUG/ForkPoolWorker-2] STREAM b'IDAT' 62 8192
2023-07-26T12:37:30.620327675Z [2023-07-26 12:37:30,620: DEBUG/ForkPoolWorker-2] STREAM b'IHDR' 16 13
2023-07-26T12:37:30.620364916Z [2023-07-26 12:37:30,620: DEBUG/ForkPoolWorker-2] STREAM b'pHYs' 41 9
2023-07-26T12:37:30.620448397Z [2023-07-26 12:37:30,620: DEBUG/ForkPoolWorker-2] STREAM b'IDAT' 62 8192
2023-07-26T12:37:30.654806267Z [2023-07-26 12:37:30,654: DEBUG/ForkPoolWorker-2] Error closing: Operation on closed image
2023-07-26T12:37:30.655607551Z [2023-07-26 12:37:30,655: INFO/ForkPoolWorker-2] create_video_task[83a8784f-29c2-49b7-9562-5217cc183b11]: 8d7ce23a-283d-4042-9e1d-a1011da064f5 - Adding subtitles
2023-07-26T12:37:30.802897107Z [2023-07-26 12:37:30,802: ERROR/ForkPoolWorker-2] create_video_task[83a8784f-29c2-49b7-9562-5217cc183b11]: MoviePy Error: creation of None failed because of the following error:
2023-07-26T12:37:30.802940246Z
2023-07-26T12:37:30.802945693Z convert-im6.q16: attempt to perform an operation not allowed by the security policy `@/tmp/tmp0_mtcd1l.txt' @ error/property.c/InterpretImageProperties/3708.
2023-07-26T12:37:30.802950732Z convert-im6.q16: no images defined `PNG32:/tmp/tmpq4kt7a67.png' @ error/convert.c/ConvertImageCommand/3229.
2023-07-26T12:37:30.802955110Z .
2023-07-26T12:37:30.802959314Z
2023-07-26T12:37:30.802963348Z .This error can be due to the fact that ImageMagick is not installed on your computer, or (for Windows users) that you didn't specify the path to the ImageMagick binary in file conf.py, or that the path you specified is incorrect
2023-07-26T12:37:31.460939434Z [2023-07-26 12:37:31,460: INFO/ForkPoolWorker-2] Task create_video_task[83a8784f-29c2-49b7-9562-5217cc183b11] succeeded in 1.5567546279926319s: '8d7ce23a-283d-4042-9e1d-a1011da064f5 create_video_task failed'
2023-07-26T12:37:31.465549618Z [2023-07-26 12:37:31,465: DEBUG/ForkPoolWorker-2] https://o4505475936092160.ingest.sentry.io:443 "POST /api/4505476598136832/envelope/ HTTP/1.1" 200 0
2023-07-26T12:37:31.474008888Z [2023-07-26 12:37:31,473: DEBUG/ForkPoolWorker-2] https://o4505475936092160.ingest.sentry.io:443 "POST /api/4505476598136832/envelope/ HTTP/1.1" 200 0
2023-07-26T12:37:31.480272685Z [2023-07-26 12:37:31,479: DEBUG/ForkPoolWorker-2] https://o4505475936092160.ingest.sentry.io:443 "POST /api/4505476598136832/envelope/ HTTP/1.1" 200 0
2023-07-26T12:37:34.251649050Z [2023-07-26 12:37:34,251: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
2023-07-26T12:37:39.252679016Z [2023-07-26 12:37:39,252: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
2023-07-26T12:37:44.250706844Z [2023-07-26 12:37:44,250: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
2023-07-26T12:37:48.773984861Z [2023-07-26 12:37:48,773: DEBUG/ForkPoolWorker-1] Starting new HTTPS connection (1): api.thenextleg.io:443
2023-07-26T12:37:49.139440107Z [2023-07-26 12:37:49,139: DEBUG/ForkPoolWorker-1] https://api.thenextleg.io:443 "GET /v2/message/i3casQMLPmc1SQcLumqN?expireMins=5 HTTP/1.1" 200 988
2023-07-26T12:37:49.143222815Z [2023-07-26 12:37:49,142: INFO/ForkPoolWorker-1] Task check_image_status_task[bc3b0dff-3e92-4ead-9b18-79f5e1512e9d] succeeded in 60.424043047998566s: None
2023-07-26T12:37:49.151257931Z [2023-07-26 12:37:49,150: DEBUG/ForkPoolWorker-1] https://o4505475936092160.ingest.sentry.io:443 "POST /api/4505476598136832/envelope/ HTTP/1.1" 200 0
2023-07-26T12:37:49.251795532Z [2023-07-26 12:37:49,251: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
2023-07-26T12:37:54.252662072Z [2023-07-26 12:37:54,252: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
2023-07-26T12:37:59.252004041Z [2023-07-26 12:37:59,251: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
`

**Comment by mobin-mazahery-school** [comment] 2024-02-03 15:23
I commented the fourth or fifth line from the bottom of the /etc/ImageMagick-6/policy.xml which says policy="path" rights="none" ...  and it worked for me. 
![image](https://github.com/Zulko/moviepy/assets/98708517/b961ddd4-ea39-4af8-8445-ee004bfaa5ed)

**Comment by griby51** [comment] 2024-03-20 17:08
> I commented the fourth or fifth line from the bottom of the /etc/ImageMagick-6/policy.xml which says policy="path" rights="none" ... and it worked for me. ![image](https://private-user-images.githubusercontent.com/98708517/302044807-b961ddd4-ea39-4af8-8445-ee004bfaa5ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NTQyMjQsIm5iZiI6MTcxMDk1MzkyNCwicGF0aCI6Ii85ODcwODUxNy8zMDIwNDQ4MDctYjk2MWRkZDQtZWEzOS00YWY4LTg0NDUtZWUwMDRiZmFhNWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDE2NTg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyMjNhZjBhZjRmYTIzOWViM2M4YzliYjIwZGQxOWJjNGRiNTlhNTM5YTBhZDBkZDdkN2FiYWZlYWE1NGJhNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UmYzF4jUaVtgPrNaEVelxYiuc5j0WFWr69BXgJOaGbM)

That's dont work for me, that work yesterday but today that dob't work, i didn't know this

**Comment by saisreesatyassss** [comment] 2024-04-07 09:48
> I have the exact same issue. The app works fine on my local machine, but I get this error when deploying on Streamlit. Does anyone have a solution?

same error

**Comment by eadmaster** [comment] 2024-04-13 21:21
i confirm changing this line fixed the issue for me:
````
  <!-- <policy domain="path" rights="none" pattern="@*"/>-->

**Comment by TheCaptainCodes** [comment] 2024-04-28 15:44
### **What to do for windows?**

I have even changed the file path in **`config_details.py`**
`IMAGEMAGICK_BINARY = os.getenv('IMAGEMAGICK_BINARY', 'C:\Program Files\ImageMagick-7.1.1-31-Q16\magick.exe')`

I even tried:
`from moviepy.config import change_settings`
`change_settings({"IMAGEMAGICK_BINARY": r"C:\Program Files\ImageMagick\\convert.exe"})`

### **What to do now? I get the same error every time:**
Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\moviepy\video\VideoClip.py", line 1137, in __init__
    subprocess_call(cmd, logger=None)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\moviepy\tools.py", line 54, in subprocess_call
    raise IOError(err.decode('utf8'))
OSError: magick.exe: label expected `@C:\Users\LENOVO\AppData\Local\Temp\tmpusxywjtr.txt' @ error/annotate.c/GetMultilineTypeMetrics/804.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Fatin\autoyt_vidmaker\main.py", line 31, in <module>
    makeFinalVideo(story, "./assets/temp/mp3/text_audio.mp3", "./assets/temp/images/antique shop.png", "./assets/temp/video/final_video.mp4")
  File "F:\Fatin\autoyt_vidmaker\final_video.py", line 14, in makeFinalVideo
    captions_clip = VideoClip(make_frame, duration=len(words))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\moviepy\video\VideoClip.py", line 86, in __init__
    self.size = self.get_frame(0).shape[:2][::-1]
                ^^^^^^^^^^^^^^^^^
  File "<decorator-gen-11>", line 2, in get_frame
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\moviepy\Clip.py", line 93, in get_frame
    return self.make_frame(t)
           ^^^^^^^^^^^^^^^^^^
  File "F:\Fatin\autoyt_vidmaker\final_video.py", line 12, in make_frame
    return TextClip(caption, fontsize=24, color='white').set_pos('center').set_duration(1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\moviepy\video\VideoClip.py", line 1146, in __init__
    raise IOError(error)
OSError: MoviePy Error: creation of None failed because of the following error:

magick.exe: label expected `@C:\Users\LENOVO\AppData\Local\Temp\tmpusxywjtr.txt' @ error/annotate.c/GetMultilineTypeMetrics/804.
.

.This error can be due to the fact that ImageMagick is not installed on your computer, or (for Windows users) that you didn't specify the path to the ImageMagick binary in file conf.py, or that the path you specified is incorrect
