### ISSUE TITLE
VideoFileClip error when launching without console

### ISSUE THREAD

**Issue by ghost** [Zulko/moviepy#1244] opened 2020-06-21 18:39 UTC
Hello, I faced a problem that when I try to use "VideoFileClip" module without console, I get error "**_Failed to execute script pyiboot01_bootstrap_**". Only the import of these methods: "**_from moviepy.video.io.VideoFileClip import VideoFileClip_**" causes such an error. Please note that if you run .pyw file without building it into .exe, or run .py directly, no errors will occur, also if you build it into a folder instead of one file (**_with --onefile flag_**), then the error also does not occur, it works without console. But if you just build the file with any "compiler" without using the console (**_with --noconsole flag_**), you get the current error. I tried to edit the code myself inside the module and redirect the output, but it did not produce any results. I use windows 8.1 64 bit and the 64 bit interpreter python.

**Comment by systemd213** [comment] 2020-06-22 14:29
I did the following tests:
1. compile .py file - works with and without --onefile flag
2. compile .pyw without building it into one file (without --onefile flag) - works, (with --onefile flag) - does not work

Again, the problem is with this module:
from moviepy.video.io.VideoFileClip import VideoFileClip

Are there any ways to build everything into one file while hiding the console?
That is to use this method: pyinstaller --onefile --noconsole script.py

**Comment by keikoro** [comment] 2022-01-13 16:13
Closing because OP deleted their user account, so we can't follow up on this issue.

**Closed by keikoro** 2022-01-13 16:13 UTC
Labels: question, video
