### ISSUE TITLE
RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.

### ISSUE THREAD

**Issue by Directory** [Zulko/moviepy#1158] opened 2020-04-24 05:10 UTC
### Expected Behavior
not getting an error

### Actual Behavior
getting the error in the title

### Steps to Reproduce the Problem
be me and try to run `from moviepy.video.io.ffmpeg_tools import ffmpeg_extract_subclip`

ffmpeg is installed with apt and i can confirm its location in `/usr/bin/`. additionally ive also executed `pip install imageio-ffmpeg` in the python virtual environment and it is installed. ive logged `platform.python_version()` to confirm i was in the 3.8.0 venv.
executing a plain interpreter terminal in the venv and trying to import it manually does not resault in an error. only during execution. the execution is in a flask application deployed with gunicorn and nginx. 

### Specifications

  - Python Version: 3.8.0
  - Moviepy Version: the newest
  - Platform Name: Ubunto server
  - Platform Version: 18.04

**Comment by Directory** [comment] 2020-04-24 05:12
i dont really know what an exe would be doing on linux anyway. but if theres some way to manually point it to `/usr/bin/ffmpeg` that might do it

**Comment by tburrows13** [comment] 2020-04-24 09:16
I'm not sure why yours isn't working, but you can specifically point it to `/usr/bin/ffmpeg` by putting the following before importing anything else from moviepy:

```
from moviepy.config import change_settings
change_settings({"FFMPEG_BINARY": "/usr/bin/ffmpeg"})
```

or you can manually edit the file `config_defaults.py`.

Note that this will change in v2.0 (#1109). Either it will be fixed, or you'll have to use an environment variable.

**Comment by Directory** [comment] 2020-04-24 20:05
even that raises the same error.
```
  File "/home/project/project/server.py", line 14, in <module>
    from moviepy.config import change_settings
  File "/home/project/env/lib/python3.8/site-packages/moviepy/config.py", line 30, in <module>
    FFMPEG_BINARY = get_exe()
  File "/home/project/env/lib/python3.8/site-packages/imageio/plugins/ffmpeg.py", line 49, in get_exe
    return imageio_ffmpeg.get_ffmpeg_exe()
  File "/home/project/env/lib/python3.8/site-packages/imageio_ffmpeg/_utils.py", line 49, in get_ffmpeg_exe
    raise RuntimeError(
RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.
```

**Comment by tburrows13** [comment] 2020-04-24 20:27
Ok, try this before importing moviepy:

```
import os
os.environ["IMAGEIO_FFMPEG_EXE"] = "/usr/bin/ffmpeg"
```

**Comment by Directory** [comment] 2020-04-24 21:22
hmm that actually does seem to work. it impors without error. ill get back with a follow up if it actually *works* works and close the issue

**Comment by tburrows13** [comment] 2020-04-24 21:26
Sure. It’s not a great solution, but maybe it will be properly fixed in v2.0.

**Closed** 2020-04-25 22:24 UTC
Labels: bug, ffmpeg

**Comment by pj-mathematician** [comment] 2020-08-04 06:08
Hi, I am also getting the same error while working in pydroid for Android (similar to linux environment)
But I am not able to solve this issue even after the `import os`. My error-
```
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  __main__.__dict__)
  File "<string>", line 4, in <module>
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/moviepy/video/io/VideoFileClip.py", line 88, in __init__
    self.reader = FFMPEG_VideoReader(filename, pix_fmt=pix_fmt,
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/moviepy/video/io/ffmpeg_reader.py", line 35, in __init__
    infos = ffmpeg_parse_infos(filename, print_infos, check_duration,
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/moviepy/video/io/ffmpeg_reader.py", line 257, in ffmpeg_parse_infos
    proc = sp.Popen(cmd, **popen_params)
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/subprocess.py", line 856, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/subprocess.py", line 1728, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/ffmpeg'
```
Any help will be appreciated :)

**Comment by FavasM** [comment] 2020-08-10 12:44
> Hi, I am also getting the same error while working in pydroid for Android (similar to linux environment)
> But I am not able to solve this issue even after the `import os`. My error-
> 
> ```
> Traceback (most recent call last):
>   File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
>     start(fakepyfile,mainpyfile)
>   File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
>     exec(open(mainpyfile).read(),  __main__.__dict__)
>   File "<string>", line 4, in <module>
>   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/moviepy/video/io/VideoFileClip.py", line 88, in __init__
>     self.reader = FFMPEG_VideoReader(filename, pix_fmt=pix_fmt,
>   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/moviepy/video/io/ffmpeg_reader.py", line 35, in __init__
>     infos = ffmpeg_parse_infos(filename, print_infos, check_duration,
>   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/moviepy/video/io/ffmpeg_reader.py", line 257, in ffmpeg_parse_infos
>     proc = sp.Popen(cmd, **popen_params)
>   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/subprocess.py", line 856, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/subprocess.py", line 1728, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/ffmpeg'
> ```
> 
> Any help will be appreciated :)

sudo apt install ffmpeg
it will fix the issue

**Comment by cheng321284** [comment] 2020-11-16 06:35
> Ok, try this before importing moviepy:
> 
> ```
> import os
> os.environ["IMAGEIO_FFMPEG_EXE"] = "/usr/bin/ffmpeg"
> ```

It works for me

**Comment by geyang** [comment] 2021-03-20 19:39
The issue is that this appears on our HPC system sporadically, during model training. 

So even if previous calls worked, this could happen during the same RunTime. There must be something pathological going on.

**Comment by patellalit1507** [comment] 2021-07-12 06:48
it shows
 RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.
while using on android

please help!

**Comment by pj-mathematician** [comment] 2021-07-12 09:12
> it shows
> RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.
> while using on android
> 
> please help!
@patellalit1507 
Termux, `apt install ffmpeg`

**Comment by wellpguedes** [comment] 2021-08-20 15:43
step 1

python3 -m pip install moviepy

step 2

apt install ffmpeg

**Comment by RAJUL555** [comment] 2021-11-07 09:53
> step 1
> 
> python3 -m pip install moviepy
> 
> step 2
> 
> apt install ffmpeg

Unfortunately, this doesn't work. Trying to run it on pydroid 3, Android version 12.

**Comment by ClaudeSerre** [comment] 2022-08-30 14:02
For those on MAC, if you install ffmpeg with Homebrew, then the path is different, so the code become : 

`import os
os.environ["IMAGEIO_FFMPEG_EXE"] = "/opt/homebrew/Cellar/ffmpeg/5.1/bin/ffmpeg"`

**Comment by M0nochrome** [comment] 2022-10-29 04:32
For those in **Windows**: backward slash and forward slash is not the same. [tburrows13](https://github.com/tburrows13) solution does work but you have to use the forward slash for the destination of ffmpeg and not backslashes. If you want to use backslashes then you have to use double backslashes:

`import os`
`os.environ["IMAGEIO_FFMPEG_EXE"] = "C:/ffmpeg/bin/ffmpeg.exe"`

or

`import os`
`os.environ["IMAGEIO_FFMPEG_EXE"] = "C:\\ffmpeg\\bin\\ffmpeg.exe"`

_(correct for your actual ffmpeg location)_

**Comment by justnpT** [comment] 2022-10-31 21:03
> For those on MAC, if you install ffmpeg with Homebrew, then the path is different, so the code become :
> 
> `import os`
> 
> `os.environ["IMAGEIO_FFMPEG_EXE"] = "/opt/homebrew/Cellar/ffmpeg/5.1/bin/ffmpeg"`

this worked for me, because I have installed ffmpeg with brew

**Comment by davidbernat** [comment] 2022-11-02 23:08
This behavior emerged for me after upgrading to MacOS Ventura. 
This dynamic loading of an environment variable is not ideal. 
Are there plans to PR this into a solution?

**Comment by davidbernat** [comment] 2022-11-08 22:09
> For those on MAC, if you install ffmpeg with Homebrew, then the path is different, so the code become :
> 
> `import os`
> 
> `os.environ["IMAGEIO_FFMPEG_EXE"] = "/opt/homebrew/Cellar/ffmpeg/5.1/bin/ffmpeg"`

I actually have a slightly different problem on MacOS: 
homebrew installs to: 
`/opt/homebrew/Cellar/ffmpeg/5.1/bin/ffmpeg`
but moviepy tries to load from:
`/opt/homebrew/Cellar/ffmpeg/5.1/bin/ffmpeg`

Where is this configured? Is there a configuration file within moviepy which can be edited?

**Comment by davidbernat** [comment] 2022-11-08 22:18
> 

Is there an equivalent environmental flag for libraries? Here's why:
My homebrew installed into `Cellar/ffmpeg/5.1.2.reinstall/...` but when that executable runs it still searches for libraries in the `/5.1.2/` directory. It seems like an error in an iOS system but this is not my expertise.

```
dyld[54363]: Library not loaded: /opt/homebrew/Cellar/ffmpeg/5.1.2/lib/libavdevice.59.dylib
  Referenced from: <D4B0734B-405C-3440-A545-A06D935C834D> /opt/homebrew/Cellar/ffmpeg/5.1.2.reinstall/bin/ffmpeg
  Reason: tried: '/opt/homebrew/Cellar/ffmpeg/5.1.2/lib/libavdevice.59.dylib' (no such file),
```

**Comment by davidbernat** [comment] 2022-11-08 22:18
> > For those on MAC, if you install ffmpeg with Homebrew, then the path is different, so the code become :
> > `import os`
> > `os.environ["IMAGEIO_FFMPEG_EXE"] = "/opt/homebrew/Cellar/ffmpeg/5.1/bin/ffmpeg"`
> 
> this worked for me, because I have installed ffmpeg with brew


Is there an equivalent environmental flag for libraries? Here's why:
My homebrew installed into `Cellar/ffmpeg/5.1.2.reinstall/...` but when that executable runs it still searches for libraries in the `/5.1.2/` directory. It seems like an error in an iOS system but this is not my expertise.

```
dyld[54363]: Library not loaded: /opt/homebrew/Cellar/ffmpeg/5.1.2/lib/libavdevice.59.dylib
  Referenced from: <D4B0734B-405C-3440-A545-A06D935C834D> /opt/homebrew/Cellar/ffmpeg/5.1.2.reinstall/bin/ffmpeg
  Reason: tried: '/opt/homebrew/Cellar/ffmpeg/5.1.2/lib/libavdevice.59.dylib' (no such file),
```

**Comment by justnpT** [comment] 2022-11-09 00:22
> > > For those on MAC, if you install ffmpeg with Homebrew, then the path is different, so the code become :
> > > `import os`
> > > `os.environ["IMAGEIO_FFMPEG_EXE"] = "/opt/homebrew/Cellar/ffmpeg/5.1/bin/ffmpeg"`
> > 
> > 
> > this worked for me, because I have installed ffmpeg with brew
> 
> Is there an equivalent environmental flag for libraries? Here's why: My homebrew installed into `Cellar/ffmpeg/5.1.2.reinstall/...` but when that executable runs it still searches for libraries in the `/5.1.2/` directory. It seems like an error in an iOS system but this is not my expertise.
> 
> ```
> dyld[54363]: Library not loaded: /opt/homebrew/Cellar/ffmpeg/5.1.2/lib/libavdevice.59.dylib
>   Referenced from: <D4B0734B-405C-3440-A545-A06D935C834D> /opt/homebrew/Cellar/ffmpeg/5.1.2.reinstall/bin/ffmpeg
>   Reason: tried: '/opt/homebrew/Cellar/ffmpeg/5.1.2/lib/libavdevice.59.dylib' (no such file),
> ```

line in my python file is contains the 5.1.2 as it is the current version (not 5.1): 
os.environ["IMAGEIO_FFMPEG_EXE"] = "/opt/homebrew/Cellar/ffmpeg/5.1.2/bin/ffmpeg"

I'm not sure what is this "5.1.2.reinstall". Why is there the "reinstall" word ? No idea, it should be clean 5.12 IMO

**Comment by davidbernat** [comment] 2022-11-09 01:02
@justnpT: Thank you. That is not the question. The name differential is connected to homebrew. The question is whether a separate library flag is in the environment variables.

**Comment by Maisa-ASM** [comment] 2023-07-05 06:13
https://github.com/imageio/imageio-ffmpeg : If you're using a Conda environment: the conda package does not include the ffmpeg executable, but instead depends on the ffmpeg package from conda-forge. Install using:

$ conda install imageio-ffmpeg -c conda-forge

**Comment by Xiaoyun-dev** [comment] 2023-08-04 17:02
I solved this issue by following the steps
1. Download the [FFmpeg package](https://www.ffmpeg.org/download.html#build-mac) from the official website.
2. Choose the **Static builds** for macOS 64-bit.
3. add the exe file to directory 
4. set env:
import os
os.environ["IMAGEIO_FFMPEG_EXE"] = "/Users/.../ffmpeg"

**Comment by lgjonathan** [comment] 2023-09-11 06:15
Setting "IMAGEIO_FFMPEG_EXE" didn't work for me.

I had to specify the path in mediapy/__init__.py

```python
class _Config:
  ffmpeg_name_or_path: _Path = r"D:\Programs\ffmpeg\bin\ffmpeg.exe" # insert  ffmpeg.exe path here
  show_save_dir: _Path | None = None
```

**Comment by am1994** [comment] 2024-01-25 14:09
For Mac users, use this command:

`brew install ffmpeg`

**Comment by germansilva45** [comment] 2024-02-09 00:17
> For Mac users, use this command:
> 
> `brew install ffmpeg`

That made the trick for me. Thank you.

**Comment by Daryldactyl** [comment] 2024-02-21 23:28
> > Hi, I am also getting the same error while working in pydroid for Android (similar to linux environment)
> > But I am not able to solve this issue even after the `import os`. My error-
> > ```
> > Traceback (most recent call last):
> >   File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
> >     start(fakepyfile,mainpyfile)
> >   File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
> >     exec(open(mainpyfile).read(),  __main__.__dict__)
> >   File "<string>", line 4, in <module>
> >   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/moviepy/video/io/VideoFileClip.py", line 88, in __init__
> >     self.reader = FFMPEG_VideoReader(filename, pix_fmt=pix_fmt,
> >   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/moviepy/video/io/ffmpeg_reader.py", line 35, in __init__
> >     infos = ffmpeg_parse_infos(filename, print_infos, check_duration,
> >   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/moviepy/video/io/ffmpeg_reader.py", line 257, in ffmpeg_parse_infos
> >     proc = sp.Popen(cmd, **popen_params)
> >   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/subprocess.py", line 856, in __init__
> >     self._execute_child(args, executable, preexec_fn, close_fds,
> >   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/subprocess.py", line 1728, in _execute_child
> >     raise child_exception_type(errno_num, err_msg, err_filename)
> > FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/ffmpeg'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Any help will be appreciated :)
> 
> sudo apt install ffmpeg it will fix the issue

brew install ffmpeg worked for me on mac!

**Comment by blackaquaindia** [comment] 2024-04-09 06:10
[Searching Followers: Spotify]
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/ripecekcu/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/ripecekcu/?__a=1&__d=dis) >>>
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/ripecekcu/?__a=1&__d=dis) >>>
Analyzing video file "/storage/emulated/0/Python/joshxantus_3329633938699010847.mp4"
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  __main__.__dict__)
  File "<string>", line 35, in <module>
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/instagrapi/mixins/video.py", line 424, in video_upload_to_story
    upload_id, width, height, duration, thumbnail = self.video_rupload(
                                                    ^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/instagrapi/mixins/video.py", line 170, in video_rupload
    width, height, duration, thumbnail = analyze_video(path, thumbnail)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/instagrapi/mixins/video.py", line 899, in analyze_video
    video = mp.VideoFileClip(str(path))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/moviepy/video/io/VideoFileClip.py", line 88, in __init__
    self.reader = FFMPEG_VideoReader(filename, pix_fmt=pix_fmt,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/moviepy/video/io/ffmpeg_reader.py", line 35, in __init__
    infos = ffmpeg_parse_infos(filename, print_infos, check_duration,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/moviepy/video/io/ffmpeg_reader.py", line 257, in ffmpeg_parse_infos
    proc = sp.Popen(cmd, **popen_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/subprocess.py", line 1028, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/imageio-ffmpeg'

[Program finished]



I tried ffmpeg also 
THIS IS FIR ANDROID ON PYDROID

**Comment by Serjobas** [comment] 2024-04-11 20:52
> I solved this issue by following the steps
> 
> 1. Download the [FFmpeg package](https://www.ffmpeg.org/download.html#build-mac) from the official website.
> 2. Choose the **Static builds** for macOS 64-bit.
> 3. add the exe file to directory
> 4. set env:
>    import os
>    os.environ["IMAGEIO_FFMPEG_EXE"] = "/Users/.../ffmpeg"

works great, thanks mate

**Comment by blackaquaindia** [comment] 2024-04-28 08:43
did anyone notice here?
we are not talking about WINDOWS or MAC

WE ARE TALKING ABOUT ANDROID SYSTEM
