### ISSUE TITLE
bug in resize method. Mask is handled incorrectly when resize is called with lambda function.

### ISSUE THREAD

**Issue by TejasBob** [Zulko/moviepy#640] opened 2017-08-29 08:56 UTC
Hi,

The method for resizing clips located in  [resize.py](https://github.com/Zulko/moviepy/blob/master/moviepy/video/fx/resize.py) is buggy ( lines 103 - 113). I came across this bug while working on a video, I tried fixing it by looking at the source code.

`if hasattr(newsize, "__call__"):     

            newsize2 = lambda t : trans_newsize(newsize(t))

            if clip.ismask:

                fun = lambda gf,t: (1.0*resizer((255 * gf(t)).astype('uint8'),
                                                 newsize2(t))/255)

            else:

                fun = lambda gf,t: resizer(gf(t).astype('uint8'),
                                          newsize2(t))

            return clip.fl(fun, keep_duration=True,
                           apply_to= (["mask"] if apply_to_mask else []))
`

Take a look at the else part. The "fun" function code works correctly for image frames but fails for mask frames as mask frame values are in the range [0,1]. The transparency values less than 1 are converted to 0 (because of uint8 type casting). 

The fix to this problem is adding condition within lambda function to incorporate mask frames. I'm attaching code to fix this. 

My bug fix:
`        
        if hasattr(newsize, "__call__"):
            
            newsize2 = lambda t : trans_newsize(newsize(t))
            
            if clip.ismask:
                
                fun = lambda gf,t: (1.0*resizer((255 * gf(t)).astype('uint8'),
                                                 newsize2(t))/255)

            else:
                
                fun = lambda gf,t: resizer(gf(t).astype('uint8'),
                                      newsize2(t)) if len(gf(t).shape) == 3 else 1.0*resizer((gf(t)*255).astype('uint8'),newsize2(t))/255

            return clip.fl(fun, keep_duration=True,
                           apply_to= (["mask"] if apply_to_mask else []))`

Note the if else condition inside lambda function.

Tejas

**Comment by kerstin** [comment] 2017-11-25 13:30
Hi @TejasBob, just a general note about GitHub issues vs. code: the point of issues is to report problems; problem fixes, on the other hand, should be submitted as pull requests.

I.e. could you create a pull request containing your fix and reference this issue when creating it?

**Comment by TejasBob** [comment] 2017-11-25 17:38
I just created a pull request. 
Thanks!

**Comment by alexzach** [comment] 2018-06-06 11:07
Actually the problem seems to be much deep: the mask clip should not come to this line at all, as there is `if clip.ismask():` check. But at some point deeper in the moviepy decorators recursions the mask clips becomes as not masks. That causes some problems with other fxs too.

**Comment by mondeja** [comment] 2021-04-15 16:10
I can't reproduce this with the current source code (moviepy *master*). So I'm closing this. Feel free to report it if you find a reproducible example with the problem.

## Executed tests

1. Add print statements to the affected conditionals:

```python
if clip.is_mask:
                print("MASK")
                def filter(get_frame, t):
                    return (
                        resizer((255 * get_frame(t)).astype("uint8"), get_new_size(t))
                        / 255.0
                    )
            else:
                print("NO MASK")
                def filter(get_frame, t):
                    return resizer(get_frame(t).astype("uint8"), get_new_size(t))
```

2. Execute simple tests:

### `is_mask=True` with scalar `ColorClip`

#### Input

```python
from moviepy.video.VideoClip import ColorClip
from moviepy.video.fx import resize

clip = (
    ColorClip(color=0.5, size=(2, 2), is_mask=True)
    .with_fps(1)
    .with_duration(1)
    .fx(resize, lambda t: 2)
)
print(clip.get_frame(0))
```

#### Output

```
MASK
[[0.49803922 0.49803922 0.49803922 0.49803922]
 [0.49803922 0.49803922 0.49803922 0.49803922]
 [0.49803922 0.49803922 0.49803922 0.49803922]
 [0.49803922 0.49803922 0.49803922 0.49803922]]
```

### `is_mask=False` with scalar `ColorClip`

#### Input

```python
from moviepy.video.VideoClip import ColorClip
from moviepy.video.fx import resize

clip = (
    ColorClip(color=0.5, size=(2, 2), is_mask=False)
    .with_fps(1)
    .with_duration(1)
    .fx(resize, lambda t: 2)
)
print(clip.get_frame(0))
```

#### Output

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 450, in <module>
    clip = ColorClip(color=.5, size=(2, 2), is_mask=False).with_fps(1).with_duration(1).fx(resize, lambda t: 2)
  File "./moviepy/video/VideoClip.py", line 1142, in __init__
    raise Exception("Color has to contain RGB of the clip")
Exception: Color has to contain RGB of the clip
```

### `is_mask=False` with RGB `ColorClip`

#### Input

```python
from moviepy.video.VideoClip import ColorClip
from moviepy.video.fx import resize

clip = (
    ColorClip(color=(125, 125, 125), size=(2, 2), is_mask=False)
    .with_fps(1)
    .with_duration(1)
    .fx(resize, lambda t: 2)
)
print(clip.get_frame(0))
```

#### Output

```
NO MASK
[[[125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]]

 [[125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]]

 [[125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]]

 [[125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]]]
```

### `is_mask=True` with RGB `ColorClip`

#### Input

```python
from moviepy.video.VideoClip import ColorClip
from moviepy.video.fx import resize

clip = (
    ColorClip(color=(125, 125, 125), size=(2, 2), is_mask=True)
    .with_fps(1)
    .with_duration(1)
    .fx(resize, lambda t: 2)
)
print(clip.get_frame(0))
```

#### Output

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 450, in <module>
    clip = ColorClip(color=(125, 125, 125), size=(2, 2), is_mask=True).with_fps(1).with_duration(1).fx(resize, lambda t: 2)
  File "./moviepy/video/VideoClip.py", line 1137, in __init__
    raise Exception("Color has to be a scalar when mask is true")
Exception: Color has to be a scalar when mask is true
```

**Closed by mondeja** 2021-04-15 16:10 UTC
Labels: bug
