### ISSUE TITLE
on_color method does not seem to work

### ISSUE THREAD

**Issue by cblument** [Zulko/moviepy#245] opened 2015-12-29 03:25 UTC
The on_color method of the VideoClip class does not seem to work.
Here is a script where I tried various ways to create a background.

https://gist.github.com/cblument/a8b424d81aa261a84fa5

In the [make_redframe function](https://gist.github.com/cblument/a8b424d81aa261a84fa5#file-movie_tests-py-L4-L15) of my test script, creating a rectangle  and setting the fill color works fine.

I would like to be able to set different fill colors and I don't know how to use pass additional parameters to the makeframe function that the VideoClip class uses.

The on_color method of the VideoClip class looked to be a way to change the background colors but when I tried to use it to set the background color to green [here](https://gist.github.com/cblument/a8b424d81aa261a84fa5#file-movie_tests-py-L48-L51) and [here](https://gist.github.com/cblument/a8b424d81aa261a84fa5#file-movie_tests-py-L53-L56) I end up with videos with black background.  Is this a bug or am I not understanding what the on_color method does?

[on_color documentation](http://zulko.github.io/moviepy/ref/VideoClip/VideoClip.html#moviepy.video.VideoClip.VideoClip.on_color)

**Comment by tburrows13** [comment] 2020-04-28 11:38
I think the issue is that colours are in the range 0-255, not 0-1, so you've set the colour to (0,1,0) which is basically black. I think that that solves the problem, and being as this issue is so old, I'm closing it now.

**Closed by tburrows13** 2020-04-28 11:38 UTC
Labels: question
