### ISSUE TITLE
Concatenating VideoClip and ImageClip of different resolutions

### ISSUE THREAD

**Issue by stnbu** [Zulko/moviepy#2016] opened 2023-07-21 16:06 UTC
I've tried many things to do this and the output consistently is ...garbled. I can elaborate on the following code and how I got there. The code:

```rust
from moviepy.editor import *
from PIL import Image
import numpy as np
video_clip = VideoFileClip("video.mov").subclip(0, 5).set_fps(24)
img = Image.open("image.jpg")
img.thumbnail(video_clip.size, Image.LANCZOS)
image_clip = ImageClip(np.array(img)).set_duration(5).set_fps(24)
result = concatenate_videoclips([video_clip, image_clip])
result.write_videofile("output.mp4", codec='libx264', fps=24)
```

I posted the output [here](https://youtu.be/cDaRi6AlEKE).

Also know/tried:
* Also tried the `resize` method and encounter: `AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'`
* Also tried `VideoFileClip` instead of `ImageClip`. I didn't really try much; I understand it gives a 1-frame video.
* Composing the two videos on top of a blank one and `image_clip.set_start(5)` with similar results.

I appreciate any help. This would suit all my simple "slideshow" needs.

**Comment by stnbu** [comment] 2023-07-21 19:52
And a [link to the script I'm working on](https://github.com/stnbu/mstudio/blob/a8d8165e4af9542c3b06ffd50a48573150dbde41/20230719.0/make.py#L15) if it's of interest.

Also, the goal is to have the image clip scaled maximally inside the target/result video's size, whatever it is. I feel like there is probably an easier way I haven't found it yet.

**Comment by keikoro** [comment] 2024-02-10 19:42
Closing this as duplicate of #2072, which seems to be the only ticket referencing the library's actual release notes.

**Closed by keikoro** 2024-02-10 19:42 UTC
Labels: question
