### ISSUE TITLE
Trouble with function VideoFileClip()

### ISSUE THREAD

**Issue by yoyomo** [Zulko/moviepy#177] opened 2015-06-09 18:34 UTC
I am using 64bit Windows with 32 bit python2.7. Every time I enter VideoFileClip("frozen_trailer.mp4") I get:
```
Traceback (most recent call last):
  File "C:\Users\armando\Documents\Workspaces\use_your_head.py", line 3, in <module>
    clip = (VideoFileClip("frozen_trailer.mp4")
  File "C:\Python27\lib\site-packages\moviepy\video\io\VideoFileClip.py", line 55, in **init**
    reader = FFMPEG_VideoReader(filename, pix_fmt=pix_fmt)
  File "C:\Python27\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 32, in **init**
    infos = ffmpeg_parse_infos(filename, print_infos, check_duration)
  File "C:\Python27\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 237, in ffmpeg_parse_infos
    proc = sp.Popen(cmd, **popen_params)
  File "C:\Python27\lib\subprocess.py", line 710, in **init**
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 is not a valid Win32 application
```

**Comment by Zulko** [comment] 2015-06-15 17:00
Interesting. Seems like imageio has registered ffmpeg64 as the right ffmpeg binary, but then the binary gets rejected as not being a valid Win32 application, maybe because 32bit Python's subprocess expects 32bits applications. Is there any reason you use 32bits Python instead of 64bits ? ccing @almarklein for awareness

**Comment by almarklein** [comment] 2015-06-16 00:13
AFAIK you can subprocess 64-bit applications from a 32 bit process. Actually, the ffmpeg exe is 32bit.

I suspect it might be that the file got corrupted during download. Can you remove the file? It's somewhere in "c:\Users\yourname\Appdata\local\imageio" (something like this).

**Comment by yoyomo** [comment] 2015-06-16 01:34
I deleted it and upgraded imageio, and now I'm getting another error. I pip-installed fx but to no avail, also tried OpenCV and Scipy and PIL but nothing:

Traceback (most recent call last):
  File "C:\Users\armando\Documents\Workspaces\use_your_head.py", line 5, in <module>
    .resize(0.3))
  File "C:\Python27\lib\site-packages\moviepy\video\fx\resize.py", line 156, in resize
    raise ImportError("fx resize needs OpenCV or Scipy or PIL")
ImportError: fx resize needs OpenCV or Scipy or PIL

**Comment by Zulko** [comment] 2015-06-16 06:34
This seems like a serious and recurring bug. What version of opencv and Scipy did you try ?

**Comment by Zulko** [comment] 2015-06-16 06:34
@almarklein  thanks !

**Comment by kerstin** [comment] 2017-02-17 19:59
This specific issue was apparently solved using [Pillow](https://github.com/python-pillow/Pillow), but might need more looking into?

**Comment by riotimus** [comment] 2018-12-28 23:53
as Zulko commented on 26 Oct 2015 at https://github.com/Zulko/moviepy/issues/221...needs to define the ffmpeg real location..

**Comment by keikoro** [comment] 2018-12-30 15:31
Linking #221 properly

**Comment by tburrows13** [comment] 2020-06-16 01:56
I'm closing this as the problem is with ffmpeg and imageio, not moviepy. The method of automatically installing ffmpeg has changed recently anyway (it now uses imageio-ffmpeg).

**Closed by tburrows13** 2020-06-16 01:56 UTC
Labels: bug
